 
/** Generated by scripts/generate-copilot-manual-content.mjs — do not edit by hand. */
import type { CopilotManualSection } from "./types";

export const COPILOT_MANUAL_GENERATED_SECTIONS: CopilotManualSection[] = [
  {
    id: "copilot",
    title: "¿Qué es Summer87 Copilot?",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Copilot es una pantalla de control para tu negocio. Te ayuda a ver cuánto dinero hay, quién te debe, qué pagos se vienen, qué clientes están atrasados y qué acciones conviene hacer primero." },
      { type: "callout", variant: "info", text: "Importante: Copilot no reemplaza a tu contador ni al sistema contable. Es una herramienta para leer la situación del negocio y tomar mejores decisiones." },
      { type: "bullets", items: ["Muestra cuánto dinero tenés disponible y qué pagos están programados.","Dice quién te debe y cuánto lleva sin pagar.","Avisa cuando algo importante cambia: un cliente paga, un vencimiento se acerca.","Sugiere qué hacer primero según la situación del negocio.","Toma los datos de tu sistema contable (Zeta) y los presenta de forma clara."] },
    ],
  },
  {
    id: "navegacion",
    title: "Cómo moverse por Copilot",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El menú lateral está organizado para que sepas dónde empezar, dónde operar y dónde consultar sin perder rutas ni funciones." },
      { type: "callout", variant: "tip", text: "Acciones vs. Alertas: Alertas cuenta qué pasó; Acciones dice qué hacer. Ambas siguen disponibles; Alertas está en Sistema para no competir con el flujo diario." },
      { type: "bullets", items: ["Hoy — resumen, prioridad diaria y caja al instante."] },
      { type: "bullets", items: ["Acciones — tareas y agenda de cobranza.","Clientes — ficha 360, cobranza y contacto.","Cartera — deuda por período y reportes.","Tesorería — caja, pagos próximos y movimientos."] },
      { type: "bullets", items: ["Datos — facturas, recibos y registros en tabla.","Reportes — cada reporte puede verse en pantalla o descargarse como PDF. Cubre cobranza, caja, ventas, ejecutivo mensual, ranking de clientes y descarga masiva de estados de cuenta.","Panorama financiero — lectura general (no reemplaza Tesorería ni Cartera).","Agentes IA — briefings de lectura; no modifican datos."] },
      { type: "bullets", items: ["Manual de uso — esta guía.","Alertas — qué pasó en el negocio (inbox de avisos).","Estado del sistema — integraciones, sincronización y salud técnica."] },
    ],
  },
  {
    id: "hoy",
    title: "Hoy — La pantalla principal",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Hoy es lo primero que deberías mirar cada mañana. Resume todo lo que está pasando en el negocio en un solo lugar." },
      { type: "callout", variant: "tip", text: "Tu día en una frase — al entrar, un bloque te dice qué hacer primero: contactar clientes vencidos, revisar agenda de cobranza, ir a Tesorería o revisar acciones. Un CTA claro para no perderse." },
      { type: "bullets", items: ["Tu día en una frase — la acción concreta sugerida con un CTA (clientes vencidos, agenda, Tesorería o acciones).","Caja disponible — dinero en Tesorería ahora. No es facturación ni deuda de clientes.","Clientes por cobrar — facturas abiertas. Es deuda de clientes, no plata en caja.","Pagos próximos — qué salidas están cargadas en Tesorería para los próximos días.","Caja después de pagos — cuánto queda si se pagan todos los compromisos cargados.","Clientes que explican el riesgo — quiénes deben más o llevan más tiempo sin pagar.","Detalle financiero del período — facturación, cobros y proyección del período seleccionado.","Próximos 30 días — escenario operativo con caja, pagos y lo que podrías cobrar.","Generar PDF — en Clientes podés descargar el reporte de deudores."] },
      { type: "bullets", items: ["Saldo actual cargado — el punto de partida. Lo cargás vos en Tesorería con la plata real que tenés en caja o cuenta.","Cobros Zeta posteriores — si un cliente paga después de que cargaste el saldo, Copilot lo suma automáticamente cuando aparece en Zeta. No tenés que registrarlo a mano.","Registros manuales — plata que ingresa o egresa pero no viene de Zeta (transferencias, adelantos, pagos realizados). Se registra en Tesorería.","Pagos programados sin confirmar — no restan hasta que los marcás como ejecutados."] },
      { type: "bullets", items: ["Si hay clientes con deuda vencida → abrí su ficha y contactá por WhatsApp o email.","Si hay pagos próximos → entrá a Tesorería para confirmar que estén cubiertos.","Si la caja después de pagos queda baja → revisá saldo y pagos en Tesorería.","Si la caja disponible parece incorrecta → verificá que el saldo en Tesorería esté actualizado.","Para ver el detalle de facturación y cobros → abrí 'Detalle financiero del período'.","Para ver escenario a 30 días → abrí 'Próximos 30 días' dentro del mismo detalle."] },
    ],
  },
  {
    id: "acciones",
    title: "Acciones — Qué hacer primero",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Acciones es la lista de cosas concretas que conviene hacer hoy. No avisa qué pasó — dice qué hacer." },
      { type: "callout", variant: "tip", text: "Inbox operativo: Prioridades = qué resolver · Agenda = a quién seguir · Alertas = qué revisar (vista previa con enlace al módulo completo)." },
      { type: "bullets", items: ["Contactar a un cliente que lleva 45 días sin pagar.","Revisar un pago que vence esta semana.","Verificar el estado de la caja antes del cierre del mes."] },
      { type: "bullets", items: ["Todas — todo junto.","Críticas — las más urgentes, las que no pueden esperar.","Cobranza — acciones relacionadas con clientes y facturas.","Tesorería — acciones relacionadas con pagos y caja.","Sistema — avisos técnicos sobre la sincronización de datos."] },
      { type: "bullets", items: ["Última gestión — canal, resultado y fecha de la última gestión registrada.","Prometió pagar — si hay una promesa activa, se muestra la fecha y el monto.","Próximo seguimiento — si agendaste un seguimiento, aparece la fecha.","La prioridad puede bajar si el cliente ya fue contactado o tiene una promesa futura.","El botón cambia a «Ver seguimiento» para ir directo al historial del cliente."] },
      { type: "bullets", items: ["Acceso directo: Acciones → pestaña Agenda de cobranza (o /copilot/acciones?tab=agenda).","También en Hoy: resumen compacto con counts y link Ver agenda.","Vencidos — seguimientos cuya fecha ya pasó, contactos incorrectos y clientes sin respuesta hace 5+ días.","Hoy — seguimientos programados para hoy. Alta prioridad: hacer antes del cierre del día.","Próximos — seguimientos futuros ordenados por fecha. Para planificar la semana.","Promesas — clientes con promesa de pago activa, separadas en vencidas (crítico) y futuras (monitorear).","Contactados — clientes contactados en los últimos 7 días sin señal pendiente. Estado 'Esperando respuesta'."] },
    ],
  },
  {
    id: "alertas",
    title: "Alertas — Historial de avisos",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Alertas guarda todos los avisos importantes del negocio. Es como la bandeja de entrada, pero para eventos del negocio." },
      { type: "callout", variant: "info", text: "Marcar como leída solo indica que ya la viste. La alerta sigue ahí para consultarla después." },
      { type: "bullets", items: ["Cobro recibido — un cliente pagó.","Cliente vencido — un cliente lleva días sin pagar.","Pago próximo — un pago vence pronto.","Pago vencido — un pago ya pasó su fecha.","Problema de sincronización — los datos no se actualizaron correctamente."] },
    ],
  },
  {
    id: "clientes",
    title: "Clientes — Directorio y ficha 360",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Clientes muestra a quién le vendés y cómo está cada relación comercial. Tocar un cliente abre su ficha 360 con encabezado fijo y pestañas reales de contenido: Resumen, Cobranza, Estado de cuenta, Facturas, Cobros, Datos y Formas de transferencia." },
      { type: "paragraph", text: "La ficha tiene dos zonas: el encabezado fijo (nombre, RUT, chips de estado, contactos, indicadores y próximo paso) y el contenido de la pestaña activa. Al cambiar de pestaña solo se muestra esa sección, sin scroll largo por toda la ficha." },
      { type: "paragraph", text: "La barra de pestañas es sticky, queda anclada al tope al hacer scroll dentro de la pestaña activa. En mobile las pestañas se pueden deslizar horizontalmente. La última pestaña visitada se recuerda durante la sesión." },
      { type: "callout", variant: "tip", text: "Próximo paso — debajo de los indicadores, un bloque destacado muestra la acción sugerida, la deuda actual y dos botones: Ver estado de cuenta y Generar cobranza." },
      { type: "callout", variant: "tip", text: "Copilot sugiere, vos decidís. Los resúmenes y acciones que muestra la ficha son lecturas automáticas. La decisión de contactar al cliente, negociar un plazo o dar de baja una deuda siempre es tuya." },
      { type: "bullets", items: ["Encabezado fijo — nombre, RUT, código, chips de estado (deuda, riesgo), contactos, indicadores (Deuda UYU/USD, Facturas pendientes, Último cobro) y Próximo paso.","Pestaña Resumen — lectura del Agente de cliente + últimos 5 movimientos comerciales con enlace 'Ver actividad completa'. No muestra cobranza ni estado de cuenta completo.","Pestaña Cobranza — Asistente de cobranza (canal, tono, mensaje, adjuntos sugeridos, WhatsApp y email) + formulario de gestión + historial de gestiones.","Pestaña Estado de cuenta — descarga de PDF, envío de estado de cuenta, deuda actual (UYU y USD) e historial de movimientos. Incluye controles de moneda y rango de fechas.","Pestaña Facturas — tabla completa de facturas emitidas con contador, estado, importe, saldo y fecha.","Pestaña Cobros — tabla completa de cobros registrados con contador, importe, medio de pago, referencia y estado.","Pestaña Datos — tarjeta con los 6 campos de identidad del cliente: Razón social, Nombre visible, Código, RUT, Email y Teléfono. Sin secciones colapsables ni información comercial.","Pestaña Formas de transferencia — gestión de aliases de pago: textos, bancos o razones sociales desde donde el cliente suele transferir. Podés agregar, editar y eliminar aliases. Se usan para la conciliación automática del extracto bancario Santander."] },
      { type: "bullets", items: ["Deuda total — suma de todas las facturas abiertas (emitidas o pendientes).","Deuda vencida — parte de esa deuda cuya fecha de vencimiento ya pasó.","% vencido — qué proporción de la deuda total ya está vencida. Cuanto más alto, más urgente."] },
      { type: "bullets", items: ["Dónde generarlo — botón Generar PDF en Hoy (bloque Clientes críticos) y en Clientes (Cartera de clientes).","Antes de descargar — elegís moneda, estado, montos mínimos, antigüedad de vencimiento y contacto.","Vista previa — el modal indica cuántos clientes entrarán con los filtros elegidos.","Antigüedad — días exactos desde la factura vencida más antigua (fecha de emisión del PDF como referencia).","UYU y USD — cada moneda va en filas separadas; los totales no se mezclan.","Columnas — cliente, moneda, deuda, vencido, días de atraso, contacto y estado.","Orden — primero pesos de mayor a menor deuda, luego dólares de mayor a menor (si aplica el filtro de moneda).","Contacto — solo muestra WhatsApp o email si el dato es válido (teléfono corto o email inválido no cuenta).","Filtros en el PDF — solo aparecen los filtros que realmente restringen el reporte; los valores por defecto no se listan.","Es informativo — no modifica datos, no marca clientes como pagados y no envía mensajes."] },
      { type: "bullets", items: ["Email — debajo del encabezado: Enviar email, Copiar email o WhatsApp si el teléfono es válido.","Teléfono — aparece en la franja Contactos, no en una pestaña aparte.","Si no hay datos de contacto → revisá los datos en tu sistema contable (Zeta)."] },
      { type: "bullets", items: ["Qué pasa — resume la situación del cliente: sin deuda, deuda al día, vencida o con promesa de pago.","Por qué importa — explica el contexto: cuánto tiene vencido, en qué moneda.","Qué hacer ahora — sugiere el próximo paso: preparar cobranza, ver seguimiento o revisar estado de cuenta.","Insights — señales operativas (vencido, promesa, última gestión). No incluye contacto ni último movimiento porque ya están arriba.","CTA — el botón lleva al asistente de cobranza, al estado de cuenta o al seguimiento.","No modifica nada. No marca facturas. No envía mensajes. Solo sugiere."] },
      { type: "bullets", items: ["Canal — elige WhatsApp o Email según como preferís contactar al cliente.","Tono — Amable para el primer aviso, Firme si ya pasó un tiempo, Urgente si la deuda lleva mucho sin atenderse.","Generar mensaje — crea el texto con los datos reales del cliente (nombre y monto).","Adjuntos sugeridos — según la deuda por moneda, Copilot muestra links para descargar Estado de cuenta UYU y/o USD. Si debe en una sola moneda, aparece solo ese PDF.","WhatsApp — no adjunta archivos automáticamente: descargá el PDF y adjuntalo manualmente al enviar el mensaje.","Email — abre tu cliente de correo con asunto y cuerpo; descargá y adjuntá el PDF antes de enviar.","Copiar mensaje — copia el texto al portapapeles para pegarlo donde quieras.","Enviar email — si el cliente tiene email cargado, abre tu cliente de correo con el texto y asunto preparados.","Abrir WhatsApp — aparece solo si el cliente tiene un celular utilizable (formato uruguayo). Al hacer clic, abre WhatsApp con el mensaje ya escrito.","Teléfono no utilizable para WhatsApp — aparece cuando hay un teléfono cargado pero es fijo o tiene formato inválido. Corregí el teléfono en Zeta para habilitarlo.","Sin teléfono cargado — el cliente no tiene teléfono registrado en el sistema."] },
      { type: "bullets", items: ["Canal — elegís cómo fue el contacto: WhatsApp, Email, Teléfono u Otro.","Resultado — qué pasó: Contactado, Prometió pagar, Sin respuesta, Contacto incorrecto, En disputa, Requiere seguimiento.","Nota — campo libre para escribir el detalle: 'prometió pagar el viernes', 'sin respuesta, llamar en 3 días', etc.","Próximo seguimiento — fecha opcional para recordar cuándo volver a contactar.","Promesa de pago — si el resultado fue 'Prometió pagar', la fecha es requerida para guardar la gestión. El monto es opcional.","Registrar gestión — guarda el registro. No modifica la deuda ni marca facturas como pagadas."] },
      { type: "bullets", items: ["Contactado — lograste comunicarte con el cliente.","Prometió pagar — el cliente se compromete a pagar en una fecha. La fecha de promesa es requerida; el monto es opcional.","Sin respuesta — llamaste o escribiste pero no contestó.","Contacto incorrecto — el número o email que tenés no es el correcto.","En disputa — el cliente no reconoce la deuda o la cuestiona.","Requiere seguimiento — necesitás volver a contactar, pero no hay más detalle por ahora."] },
      { type: "bullets", items: ["Registrar una gestión hace que Acciones y Agentes reconozcan el estado real del cliente, sin repetir la misma recomendación de contacto.","Si el cliente fue contactado recientemente, Copilot lo muestra como 'ya contactado' o 'esperando respuesta' en lugar de 'priorizar cobranza'.","Si hay una promesa de pago futura, los Agentes sugieren monitorearla en lugar de contactar.","Si la promesa vence sin confirmación de pago, la prioridad sube automáticamente.","Si el resultado fue 'Sin respuesta' hace más de 5 días, vuelve a ser prioritario.","Si el resultado fue 'Contacto incorrecto', la prioridad se mantiene alta porque no hubo contacto útil.","La deuda nunca desaparece. Solo cambia el copy y el tono de la recomendación."] },
      { type: "bullets", items: ["Botón Descargar PDF — aparece en la sección Estado de cuenta histórico de la ficha.","Incluye todos los movimientos del cliente: facturas emitidas, cobros recibidos y saldo acumulado.","Cada factura muestra su concepto/ítem real (viene de Zeta) debajo del movimiento principal.","Cada recibo muestra la caja o medio de cobro como línea secundaria.","Las facturas con ajuste van en columna Haber (descuentan saldo), no como deuda a cobrar.","Separa UYU y USD en bloques independientes. No mezcla monedas.","Usa el modo ledger: incluye también registros archivados para un historial completo.","El PDF no modifica datos — es solo lectura de lo sincronizado desde Zeta.","El archivo se descarga directamente en el navegador."] },
      { type: "bullets", items: ["Elegí el canal: Email o WhatsApp.","Elegí la moneda del mensaje: Pesos (UYU) o Dólares (USD) — el saldo del texto se ajusta automáticamente.","Adjuntos sugeridos — Copilot ofrece descargar Estado de cuenta UYU y/o USD según la deuda real del cliente (no según la moneda del mensaje).","Elegí el tono: Amable (informal), Firme (formal exigente) o Breve (mensaje corto).","El mensaje se genera con el período del año actual al día de hoy y el saldo vigente del cliente.","Botón Copiar mensaje — copia el texto al portapapeles.","Botón Abrir email — abre el cliente de correo con destinatario, asunto y cuerpo pre-cargados.","Botón Abrir WhatsApp — abre WhatsApp Web o la app con el mensaje pre-cargado.","Si el cliente no tiene email registrado, el botón de email queda deshabilitado.","Si el cliente no tiene celular apto para WhatsApp, ese botón queda deshabilitado.","Los PDFs no se adjuntan automáticamente — descargalos desde Adjuntos sugeridos y adjuntalos manualmente antes de enviar.","Después de Copiar, Abrir email o Abrir WhatsApp, aparece el botón Registrar gestión. Al hacerlo, el formulario de Gestión de cobranza se completa automáticamente con el canal y una nota del período enviado.","Si el formulario de cobranza ya tiene texto, en lugar de pisarlo aparece una sugerencia que podés aplicar o ignorar."] },
      { type: "bullets", items: ["Buscador — busca en texto libre: cliente, número, RUT, concepto, método de cobro o estado.","Listado — alternás entre Activos, Inactivos o Todos sin recargar la página.","Contador — muestra cuántos registros coinciden con los filtros activos.","Período (Facturas y Recibos) — filtrá por Mes y año, Rango de fechas o Todo. Botones rápidos: Mes actual, Hoy (Recibos) y Limpiar.","Chips Facturas — Todos / Con saldo / Ajustes y Pesos / Dólares.","Chips Recibos — Pesos / Dólares.","Al hacer clic en cualquier registro se abre el panel lateral con el detalle completo.","Los IDs técnicos de Zeta quedan en el bloque «Datos técnicos» dentro del panel — no aparecen en la vista principal."] },
      { type: "bullets", items: ["Datos — panel lateral rápido: código, deuda, facturas y contactos básicos.","Ficha completa (esta sección) — pestañas reales con contenido separado. Cada pestaña muestra solo su información sin scroll por toda la ficha.","Detalle técnico — sección colapsada dentro de la pestaña Datos. Solo para casos avanzados."] },
      { type: "bullets", items: ["Formas de transferencia — podés registrar uno o más textos que identifican cómo transfiere ese cliente (por ejemplo: 'DOLBY SOCIEDAD ANONIMA', 'ACME SA', 'PETROVIC SOLUTIONS').","Agregá desde la ficha del cliente: sección «Formas de transferencia» → botón Agregar.","Cada alias tiene un campo de texto obligatorio (3-300 caracteres) y una nota opcional.","Podés editar o eliminar cualquier alias en cualquier momento.","Si eliminás un alias, Copilot deja de usarlo para la conciliación Santander a partir del siguiente import.","La búsqueda en la lista de clientes incluye aliases: si buscás 'DOLBY', aparecen los clientes con ese alias aunque el nombre del cliente sea otro.","Si el cliente no tiene aliases pero tiene una forma de transferencia cargada en el sistema anterior, aparece como sugerencia en el estado vacío para que la migrés con el botón Agregar.","Permisos — solo usuarios con rol de escritura pueden agregar, editar o eliminar aliases. Usuarios de solo lectura ven la lista pero no pueden modificarla."] },
      { type: "glossary", entries: [{"term":"Factura emitida","definition":"Se emitió pero aún no fue pagada ni venció."},{"term":"Factura vencida","definition":"Pasó su fecha de vencimiento sin cobro registrado."},{"term":"Factura pagada","definition":"Hay un cobro registrado que la cubre."},{"term":"Cobro registrado","definition":"Pago que el cliente realizó, registrado en el sistema contable."}] },
    ],
  },
  {
    id: "cartera",
    title: "Cartera — Quién te debe y cuánto",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Cartera muestra el dinero que los clientes te deben. Es la vista de cobranza: cuánto hay pendiente, qué está vencido y quiénes tienen más urgencia." },
      { type: "callout", variant: "info", text: "Cartera ≠ Caja. Lo que ves en Cartera es deuda que los clientes todavía no pagaron. No es plata disponible. Entra en caja solo cuando el cliente paga y el cobro aparece en Zeta. El Dinero disponible viene de Tesorería, no de Cartera." },
      { type: "glossary", entries: [{"term":"Al día","definition":"Facturas que aún no vencieron."},{"term":"1 a 30 días","definition":"Recién vencido. Conviene avisar."},{"term":"31 a 60 días","definition":"Ya lleva un mes. Priorizar el contacto."},{"term":"61 a 90 días","definition":"Problema real. Gestión urgente."},{"term":"Más de 90 días","definition":"Muy difícil de cobrar. Acción inmediata."}] },
    ],
  },
  {
    id: "tesoreria",
    title: "Tesorería — Caja, pagos y compromisos",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Tesorería es donde cargás y gestionás el dinero operativo: el saldo actual de caja, los egresos y pagos que no vienen de Zeta. Es la fuente del número Dinero disponible que ves en Hoy." },
      { type: "bullets", items: ["No es facturación anual. No es lo que te deben. No es el total cobrado histórico.","Es el punto de partida: la plata que tenés ahora, que vos conocés mejor que nadie.","Se carga en Tesorería → panel de caja disponible → botón Editar saldo actual.","Podés actualizarlo cuando quieras. Cada vez que lo actualizás, la fecha de corte se resetea a ese día.","UYU y USD se cargan por separado."] },
      { type: "bullets", items: ["Si un cliente paga después de que cargaste el saldo, el cobro aparece en Zeta y Copilot lo suma solo al Dinero disponible.","Si el cobro ocurrió antes de la fecha en que cargaste el saldo, no se suma de nuevo — ya estaba incluido en el saldo que cargaste.","Esto evita duplicar: el saldo que cargaste ya refleja todo lo cobrado hasta ese momento.","Los cobros anulados o cancelados no suman aunque tengan fecha posterior."] },
      { type: "bullets", items: ["Registrá en Tesorería los pagos que hacés: sueldos, impuestos, proveedores, gastos operativos.","Los egresos confirmados restan del Dinero disponible desde la fecha en que ocurrieron.","Los pagos programados (fecha futura o sin confirmar) no restan hasta que los ejecutás.","Los ingresos manuales (no de facturas Zeta) también se registran acá y suman al disponible.","Caja manual → Movimientos de entrada y salida registrados por vos."] },
      { type: "bullets", items: ["Soporta CSV, Excel y PDF Santander con texto extraíble. PDF no usa OCR. El importador reconoce el extracto por la estructura de la tabla aunque el logo Santander no sea texto extraíble.","Usuario y modo demo pueden generar vista previa (no persiste datos). Guardar o importar el extracto requiere superadmin.","Generá un preview antes de guardar: ves fecha, monto, tipo y un estado de coincidencia por fila.","Coincide — el movimiento del banco parece ya estar en Tesorería (y en Zeta si aplica).","Falta en Copilot — hay señal en Zeta o es un cobro en banco sin movimiento equivalente en Tesorería.","Falta en Zeta — está en Tesorería pero no hay recibo Zeta en la ventana de fechas.","Posible coincidencia — monto, fecha o texto parecen relacionados; conviene revisar manualmente.","Cliente sugerido por forma de transferencia — Copilot detectó que la descripción del movimiento contiene el texto de una de las formas de transferencia registradas para ese cliente. Conviene validar antes de confirmar.","Las formas de transferencia se configuran en la ficha de cada cliente (sección Formas de transferencia). Podés registrar varios aliases por cliente.","Si el PDF no puede leerse, exportá CSV o Excel desde Santander.","No modifica caja automáticamente ni crea recibos en Zeta. Guardar solo almacena el extracto para conciliación.","Para impactar caja tenés que crear o confirmar un movimiento de Tesorería por separado."] },
      { type: "bullets", items: ["Caja — saldo disponible cargado al corte. Arriba del formulario: ¿Qué querés registrar? (Ingreso, Egreso o Pago programado).","Pagos próximos — pagos con fecha futura, recurrentes y obligaciones; no afectan caja hasta confirmarse.","Movimientos — ingresos y egresos confirmados que ajustan tu caja. Incluye importador bancario (extracto CSV/XLSX)."] },
      { type: "bullets", items: ["No marca ninguna factura como pagada desde Tesorería.","No modifica datos en Zeta.","No duplica cobros: si el cobro es anterior al saldo cargado, no se suma de nuevo.","UYU y USD se calculan por separado — no se mezclan.","Los cobros de clientes vienen de Zeta; los egresos operativos se registran en Tesorería."] },
    ],
  },
  {
    id: "finanzas",
    title: "Panorama financiero — Lectura ejecutiva",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Panorama financiero es el panel ejecutivo para CEO y contador: ventas, cobros, deuda, caja y evolución del negocio. No reemplaza Cartera ni Tesorería para operar el día a día ni es un cierre contable formal." },
      { type: "callout", variant: "info", text: "Si el mes actual está en curso, Finanzas no presenta “este mes vs el anterior” como comparación principal de performance: muestra el acumulado parcial y compara meses cerrados (ej. Mayo vs Abril). Para cierre contable formal, validá con tu contador." },
      { type: "bullets", items: ["Fecha de corte — día hasta el cual están calculados los números (hoy operativo).","Período actual — desde el 1.º del mes hasta la fecha de corte (mes en curso, lectura parcial).","Último mes cerrado — mes calendario completo anterior; Finanzas lo usa para comparar desempeño mensual cuando el mes actual recién empieza.","Vista por capas — resumen ejecutivo (6 métricas), comparación principal, evolución, riesgo de cobranza y proyección visibles; detalle avanzado colapsado.","Resumen ejecutivo — hasta 6 KPIs combinando UYU y USD, con 3 bullets de lectura integrados.","Comparación principal — una tabla por moneda (selector UYU/USD): último mes cerrado vs anterior; el mes en curso aparece como nota aparte.","Ventas — facturas del período. Fuente distinta a cobros y a deuda.","Cobros — recibos por fecha de recibo; pueden superar ventas del período si se recupera deuda anterior.","Deuda total y vencida — saldo de clientes en Cartera al corte; no es lo mismo que cobros ni caja.","Caja disponible — Tesorería (baseline + movimientos); no es facturación ni cierre bancario.","Proyección 30 días — estimación operativa compacta (caja + cobros esperados − pagos cargados).","Riesgo de cobranza — un bloque con selector UYU/USD (deuda, vencido, top 5).","Detalle avanzado — colapsado: clientes, desglose contable, semana vs semana y enlace fiscal.","Evolución comercial — gráfico principal (6 meses por defecto); tabla colapsada «Ver tabla de evolución».","Obligaciones fiscales — al final de la página, fuera del detalle avanzado."] },
    ],
  },
  {
    id: "datos",
    title: "Datos — Consulta de registros base",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Datos es una vista de consulta directa. Podés ver los registros base que usa Copilot: clientes, facturas, recibos, pagos y obligaciones fiscales." },
      { type: "paragraph", text: "Los clientes se sincronizan automáticamente desde el sistema contable (Zeta). Crearlos a mano podría generar duplicados o registros que no coincidan con los datos reales. Por eso no hay botón de nuevo cliente en esta sección." },
      { type: "callout", variant: "info", text: "Datos es para consultar y verificar, no para operar. Para gestión diaria usá Cartera, Tesorería o Acciones." },
      { type: "bullets", items: ["Clientes — directorio completo con datos de contacto.","Facturas — todas las facturas por período, con saldo y estado.","Recibos — cobros con número real, cliente, monto, moneda y método. Filtros por período, rango de fechas y moneda.","Pagos — pagos fiscales y a proveedores.","Obligaciones fiscales — vencimientos tributarios."] },
      { type: "bullets", items: ["Datos → consulta rápida: código, RUT, teléfono, deuda actual y facturas recientes.","Al tocar un cliente aparece un panel lateral con deuda, facturas, recibos y contactos.","Ver ficha completa","Si solo querés confirmar un dato, usá el panel lateral. Si vas a gestionar al cliente, abrí la ficha completa."] },
    ],
  },
  {
    id: "agentes",
    title: "Agentes IA — Sistema coordinado de asistentes",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Agentes IA son asistentes que leen el Copilot y te ayudan a ordenar qué revisar primero. Trabajan en conjunto: cada agente mira una parte del negocio, y el sistema combina lo que encontraron para darte una visión unificada." },
      { type: "callout", variant: "info", text: "Los agentes no ejecutan acciones. No pagan, no borran, no envían mensajes automáticamente. Solo leen datos, ordenan prioridades y te llevan al módulo correcto. Vos siempre decidís qué hacer." },
      { type: "bullets", items: ["Va arriba de todo y resume el estado global: Bajo, En atención o Crítico.","Muestra hasta 5 prioridades globales ordenadas por urgencia.","Incluye el próximo paso recomendado para arrancar por el módulo correcto.","Debajo aparecen el Agente de Riesgo y luego los agentes operativos.","No mezcla monedas: UYU y USD se tratan por separado.","Si falta algún dato, puede mostrar una lectura parcial sin romper la pantalla."] },
      { type: "bullets", items: ["Cada card explica qué analiza ese agente.","Cada una muestra su estado actual y un resumen corto.","Cada agente enseña hasta 3 prioridades internas para no sobrecargar la lectura.","Cada card tiene un CTA principal para ir al módulo correcto.","La idea es entender la pantalla en segundos y después entrar al detalle donde corresponda."] },
      { type: "bullets", items: ["Detecta problemas de sincronización, riesgo de caja y clientes vencidos.","Indica qué cambió desde la última vez.","Sugiere el próximo paso concreto.","Usa reglas del sistema, no reemplaza tu criterio."] },
      { type: "bullets", items: ["Clientes vencidos ordenados por monto, de mayor a menor.","Promesas de pago vencidas — si un cliente prometió pagar y la fecha ya pasó.","Seguimientos vencidos — si tenés un próximo contacto programado para hoy o antes.","Reintentos — clientes que no respondieron hace 2 o más días.","Si hay más de 3 clientes vencidos, muestra un resumen de cartera.","No sugiere enviar mensajes automáticamente."] },
      { type: "bullets", items: ["Próximo seguimiento — si agendaste una fecha futura, aparece en Acciones con badge 'Seguimiento programado' (azul). Cuando llega el día, el badge cambia a 'Seguimiento hoy' (ámbar). Si la fecha pasó sin registrar contacto, aparece como 'Seguimiento vencido' (rojo) con prioridad alta.","Promesa de pago — si el cliente prometió pagar y la fecha llegó sin confirmación, aparece como prioridad crítica.","Promesa futura — si la promesa es para más adelante, aparece como baja prioridad mientras no venza.","Sin respuesta — si la última gestión fue 'Sin respuesta' y pasaron 2 o más días, sugiere reintentar el contacto.","Contacto incorrecto — si registraste 'Contacto incorrecto', el agente lo marca como prioridad para actualizar los datos."] },
      { type: "bullets", items: ["Pagos vencidos — si hay obligaciones con fecha pasada, las muestra como prioridad crítica.","Riesgo de caja — si la caja puede quedar ajustada después de los pagos próximos.","Vence hoy — pagos programados para hoy, para confirmar antes de cerrar el día.","Próximos 1-3 días — compromisos inminentes que conviene revisar con anticipación.","Próximos 7 días — compromisos de la semana para planificación.","Solo lee notificaciones. No toca pagos ni saldos."] },
      { type: "bullets", items: ["Sincronización fallida — si una actualización de datos no se completó, lo muestra como prioridad.","Fuente externa con problemas — si Zeta u otra fuente falla, informa de forma simple.","Datos desactualizados — si el proceso no se ejecutó en la ventana esperada.","Inconsistencias detectadas — si hay datos que no coinciden entre fuentes.","Todo bien — si no hay señales de problema, muestra estado estable.","No modifica datos ni reinicia sincronizaciones."] },
      { type: "bullets", items: ["Riesgo de liquidez — si la lectura financiera muestra riesgo crítico o alto, lo informa como prioridad.","Caja en riesgo — si una notificación indica que los egresos pueden superar la caja disponible.","Cartera vencida — si hay clientes con deuda vencida que pueden afectar la cobranza esperada.","Egresos próximos — pagos vencidos o con vencimiento próximo que pueden impactar el flujo de caja.","Datos parciales — si la lectura financiera puede estar incompleta, avisa para que lo confirmes.","Solo lee datos. No inventa montos. No ejecuta ninguna acción."] },
      { type: "bullets", items: ["Revisar caja — si hay pagos vencidos, caja ajustada o compromisos importantes.","Revisar cobranza — si hay deuda vencida, promesas caídas o seguimientos pendientes.","Validar datos — si conviene revisar la actualización antes de decidir.","Ver Finanzas — si la lectura financiera general requiere monitoreo.","No tapa las prioridades específicas: solo te indica dónde mirar primero."] },
      { type: "bullets", items: ["Resume la situación de un cliente: sin deuda, al día, vencida o con promesa.","Dice qué pasa, por qué importa y qué hacer ahora para ese cliente específico.","Puede sugerir preparar cobranza, ver seguimiento, ver contactos o revisar actualización.","No modifica datos. No envía mensajes. No marca facturas como pagadas.","El usuario decide si contacta, genera un mensaje o registra una gestión."] },
      { type: "bullets", items: ["Pueden leer información, resumir, priorizar y sugerir el siguiente paso.","No pueden pagar, borrar, modificar importes ni enviar mensajes automáticamente.","No pueden marcar facturas como pagadas.","Vos siempre decidís qué hacer después de leer la recomendación."] },
      { type: "bullets", items: ["Alertas — priorizacion de avisos del sistema."] },
      { type: "glossary", entries: [{"term":"Crítica","definition":"Requiere atención inmediata. Puede afectar caja o datos."},{"term":"Alta","definition":"Importante. Conviene atenderla hoy."},{"term":"Media","definition":"Para revisar cuando puedas, sin urgencia inmediata."},{"term":"Baja","definition":"Informativa. Puede esperar."}] },
    ],
  },
  {
    id: "reportes",
    title: "Reportes — vista en pantalla y PDF",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Reportes centraliza los 6 reportes operativos, organizados en tres grupos: Cobranza, Finanzas y Clientes. Cada reporte tiene dos modos de uso:" },
      { type: "bullets", items: ["Ver reporte — abre una vista previa dentro de Copilot con filtros, resumen de métricas y tabla. Ideal para consulta rápida sin descargar nada.","Generar PDF — descarga el reporte como archivo profesional para enviar, imprimir o archivar.","Ambos modos usan los mismos datos y cálculos. No hay diferencia en los números."] },
      { type: "bullets", items: ["Deudores — clientes con deuda, moneda, antigüedad y contacto. Los filtros se aplican en tiempo real en la vista previa. Cuando el filtro de moneda es 'UYU + USD', el PDF separa los clientes en dos secciones (Pesos y Dólares) sin mezclar monedas.","Cobranza mensual — cobros registrados del mes por moneda. Incluye fecha, número de recibo, cliente e importe.","Caja mensual — movimientos del período con saldo inicial, ingresos, egresos y saldo acumulado. Ingresos en verde, egresos en rojo.","Ventas — detalle de facturas del período por moneda (fecha, número, cliente e importe), con deduplicación de comprobantes Zeta y total al pie.","Ejecutivo mensual — resumen CEO: indicadores clave, top 5 clientes, top 5 deudores, estado de caja y nivel de riesgo (Bajo / Atención / Crítico).","Clientes principales — ranking ordenable por facturación, deuda total o deuda vencida. Muestra participación y nivel de riesgo por cliente.","Estado de cuenta por cliente — vista previa sin filtro de mes/año: muestra saldos vigentes desde 2026 y selector de moneda (Pesos, Dólares o UYU + USD). El PDF respeta la moneda elegida. Si superás el límite de descargas, verás: «Demasiadas descargas. Esperá unos segundos e intentá de nuevo.»","Estado de cuenta individual — se genera desde la ficha de cada cliente (pestaña Estado de cuenta).","Los reportes son de solo lectura: no modifican facturas, caja ni gestiones.","Nunca se suman UYU + USD entre sí: cada moneda tiene su propia sección en el PDF, sin conversión ni combinación."] },
    ],
  },
  {
    id: "operacional",
    title: "Estado del sistema — Sincronización y salud técnica",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Estado del sistema (antes Operacional) muestra si los datos se están actualizando correctamente y la salud de la integración con Zeta." },
      { type: "callout", variant: "info", text: "Al entrar verás Confianza del dato: última actualización, cantidad de clientes/facturas/recibos sincronizados y si hay conflictos." },
      { type: "bullets", items: ["Cuándo fue la última actualización de datos.","Si la conexión con el sistema contable está funcionando.","Cuántas actualizaciones salieron bien y cuántas fallaron.","El estado general de los flujos de datos."] },
    ],
  },
  {
    id: "estado",
    title: "Estado: Atención / Estable / Crítico",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El estado del negocio aparece en la parte superior de la pantalla y en algunas páginas como Hoy y Operacional. Te indica de un vistazo si todo está bien o si hay algo para atender." },
      { type: "callout", variant: "tip", text: "Al tocar o hacer clic sobre el estado se despliega el detalle: qué alertas están activas, cuáles son críticas y cuáles son solo informativas." },
      { type: "status", entries: [{"level":"ok","title":"Estable","description":"Todo está dentro de lo esperado. Podés operar con normalidad."},{"level":"warning","title":"Atención","description":"Hay algo para revisar. No es urgente, pero conviene no ignorarlo. Tocar el estado muestra el detalle."},{"level":"critical","title":"Crítico","description":"Hay algo importante que puede afectar caja, pagos o la calidad de los datos. Revisarlo pronto."}] },
    ],
  },
  {
    id: "campana",
    title: "Campana de notificaciones",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "La campana aparece en la parte superior de la pantalla. Cuando tiene un número rojo, significa que hay novedades sin leer." },
      { type: "bullets", items: ["Un cliente pagó una factura.","Un cliente quedó con deuda vencida.","Un pago importante vence pronto.","Un pago ya pasó su fecha sin registrarse.","Hubo un problema en la actualización de datos."] },
      { type: "bullets", items: ["Tocar el botón de la campana abre el panel de notificaciones.","Cada notificación tiene un link para ir directo al detalle.","«Marcar todas como leídas» quita el número rojo — no borra las notificaciones.","«Ver todas» lleva al listado completo en Alertas."] },
    ],
  },
  {
    id: "problemas",
    title: "¿Qué hacer si algo aparece en rojo?",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Ver algo en rojo no significa que el negocio está en crisis. Puede ser una alerta importante o simplemente un dato para revisar." },
    ],
  },
  {
    id: "roles-permisos",
    title: "Roles y permisos",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Copilot tiene dos roles principales: Superadmin y Usuario. El acceso detallado a cada módulo se configura con permisos Ver y Modificar desde el Panel administrativo." },
      { type: "roles", entries: [{"role":"superadmin","label":"Superadmin","description":"Acceso total. Puede leer y modificar cualquier dato de la empresa. El único que puede administrar usuarios, roles y permisos."},{"role":"usuario","label":"Usuario","description":"Rol base. El acceso a cada módulo se define individualmente con los permisos Ver y Modificar. Por defecto: solo lectura en todo."}] },
      { type: "callout", variant: "info", text: "Los permisos se configuran por módulo desde el Panel administrativo (solo superadmin). Ver da acceso de lectura; Modificar da acceso de escritura e incluye Ver automáticamente. Sin ninguno de los dos, el módulo no aparece en el menú." },
      { type: "bullets", items: ["Navegar por todas las secciones permitidas según rol y permisos.","Ver dashboards, fichas de clientes, movimientos y deuda (donde haya acceso de lectura).","Abrir reportes en pantalla y descargar PDFs — son operaciones de lectura.","Generar vista previa del importador Santander — no guarda ni modifica caja.","Consultar alertas, notificaciones y Agentes IA."] },
      { type: "bullets", items: ["Cargar ingresos, egresos o ajustes en Tesorería (requiere permiso Modificar en Tesorería o superadmin).","Registrar gestiones de cobranza (requiere permiso Modificar en Acciones o superadmin).","Ejecutar sincronizaciones manuales (solo superadmin).","Crear, editar o eliminar usuarios (solo superadmin vía Panel administrativo).","Acceder al Panel administrativo (solo superadmin)."] },
      { type: "bullets", items: ["Reporte de deudores.","Cobranza mensual.","Caja mensual.","Ventas.","Ejecutivo mensual.","Clientes principales.","Estado de cuenta masivo (desde Reportes, por moneda).","Estado de cuenta individual (desde la ficha de cada cliente)."] },
    ],
  },
  {
    id: "admin",
    title: "Panel administrativo",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El Panel administrativo es exclusivo del superadmin. Permite crear usuarios, asignar roles y configurar qué puede ver y modificar cada persona en la empresa." },
      { type: "callout", variant: "warning", text: "Solo superadmin puede acceder a /copilot/admin. Cualquier otro usuario que intente entrar es redirigido a Hoy." },
      {
        type: "subsection",
        title: "Cómo crear un usuario",
        blocks: [
          { type: "steps", items: ["Ir a Panel administrativo → Nuevo usuario.","Ingresar email, nombre completo y rol (Superadmin o Usuario).","Indicar un PIN temporal o dejarlo vacío para que se genere automáticamente.","Hacer clic en Crear usuario.","El PIN temporal se muestra UNA SOLA VEZ — anotarlo y entregarlo al usuario de forma segura.","El usuario puede cambiar su PIN luego desde el perfil (si aplica) o el superadmin puede resetearlo."] },
        ],
      },
      {
        type: "subsection",
        title: "Roles disponibles",
        blocks: [
          { type: "bullets", items: ["Superadmin — acceso total a todos los módulos. Puede gestionar usuarios, roles y permisos. El único que accede al Panel administrativo.","Usuario — rol base de solo lectura. Puede navegar, consultar y descargar reportes. No puede modificar datos operativos."] },
        ],
      },
      {
        type: "subsection",
        title: "Qué significa cada nivel de acceso",
        blocks: [
          { type: "bullets", items: ["Sin acceso — el módulo desaparece del menú lateral y la URL queda bloqueada. Si el usuario intenta entrar manualmente, el sistema lo redirige a Hoy o muestra un mensaje de acceso denegado.","Ver — puede navegar, ver datos y descargar PDFs del módulo.","Modificar — puede leer y también crear, editar o eliminar registros en ese módulo. Marcar Modificar activa Ver automáticamente."] },
        ],
      },
      {
        type: "subsection",
        title: "Cómo editar permisos de un usuario",
        blocks: [
          { type: "steps", items: ["En la tabla de usuarios, hacer clic en el ícono de lápiz (Editar permisos).","Se abre un modal con la tabla de módulos.","Marcar Ver para dar acceso de lectura a un módulo. Marcar Modificar para dar acceso de escritura (incluye Ver automáticamente). Desmarcar Ver quita ambos accesos.","Hacer clic en Guardar cambios.","Los cambios aplican en el próximo acceso del usuario (o inmediatamente si recarga la página)."] },
        ],
      },
      {
        type: "subsection",
        title: "Cómo resetear el PIN de un usuario",
        blocks: [
          { type: "steps", items: ["En la tabla de usuarios, hacer clic en el ícono de llave (Resetear PIN).","Confirmar la acción en el popup.","El nuevo PIN temporal se muestra una sola vez.","La sesión activa del usuario se invalida automáticamente."] },
        ],
      },
      {
        type: "subsection",
        title: "Cómo eliminar un usuario",
        blocks: [
          { type: "steps", items: ["En la tabla de usuarios, hacer clic en el ícono de papelera (Eliminar usuario).","Se abre un modal de confirmación.","Escribir ELIMINAR para confirmar.","Hacer clic en Eliminar usuario.","El usuario pierde acceso inmediatamente. Esta acción no se puede deshacer desde la interfaz."] },
          { type: "callout", variant: "warning", text: "No se puede eliminar el único superadmin activo. El sistema lo bloquea para proteger el acceso administrativo." },
        ],
      },
      {
        type: "subsection",
        title: "Recomendaciones de seguridad",
        blocks: [
          { type: "bullets", items: ["No compartir la cuenta superadmin entre varias personas.","Crear una cuenta separada para cada persona del equipo.","Mantener siempre al menos un superadmin activo (el sistema lo bloquea si intentás eliminar el último).","El PIN temporal que se muestra al crear o resetear un usuario debe entregarse en forma segura (no por email sin encriptar).","Revisar periódicamente la lista de usuarios activos y eliminar accesos que ya no correspondan."] },
        ],
      },
    ],
  },
  {
    id: "inicio-sesion",
    title: "Inicio de sesión",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El acceso a Copilot es con usuario y PIN en la pantalla de login. No usa enlaces externos ni registro público." },
      { type: "steps", items: ["Ir a /login.","Ingresar Usuario y PIN provistos por quien administra la empresa.","Pulsar Entrar.","Si las credenciales son válidas, Copilot redirige a /copilot/hoy."] },
      { type: "bullets", items: ["Superadmin, usuario y demo_readonly usan el mismo formulario; el rol define permisos después del login.","En solo lectura verás un badge en la barra superior (Solo lectura o Demo en móvil).","Superadmin no tiene badge y puede modificar datos operativos."] },
    ],
  },
  {
    id: "importador-santander",
    title: "Importador bancario Santander",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "En Tesorería → Movimientos podés subir extractos CSV, Excel o PDF exportados desde Santander para conciliar con Copilot y Zeta." },
      { type: "bullets", items: ["Formatos: CSV, Excel (XLSX) y PDF con texto extraíble (sin OCR).","Detección USD y UYU según el extracto.","Usuario y demo_readonly: vista previa permitida (no persiste ni modifica caja).","Guardar o importar extracto: solo superadmin.","Cuenta del extracto debe ser compatible con la cuenta seleccionada; si no, el guardado se bloquea.","Estados por fila: Coincide, Falta en Copilot, Falta en Zeta, Posible coincidencia.","Preview no crea recibos en Zeta ni movimientos de caja automáticos.","Para impactar caja registrá o confirmá el movimiento en Tesorería por separado."] },
      { type: "callout", variant: "warning", text: "Guardar requiere superadmin. La vista previa no modifica caja." },
    ],
  },
  {
    id: "rutinas",
    title: "Rutinas recomendadas",
    includeInToc: true,
    blocks: [
      {
        type: "subsection",
        title: "Copilot en 5 minutos",
        blocks: [
          { type: "steps", items: ["Abrí Hoy — es la pantalla principal. Muestra caja disponible, deuda de clientes y prioridad del día.","Mirá Acciones — ahí están las cosas concretas que conviene hacer: clientes a llamar, cobros a registrar.","Si hay clientes vencidos → abrí su ficha y contactá por WhatsApp o email directamente desde Copilot.","Si hay pagos próximos → entrá a Tesorería para ver caja real y confirmar que estén cubiertos.","Si querés la foto completa del negocio → Cartera para deuda y antigüedad, Finanzas para panorama general."] },
        ],
      },
      {
        type: "subsection",
        title: "Flujo recomendado del día",
        blocks: [
          { type: "paragraph", text: "Si solo tenés 10 minutos, hacé esto en orden." },
          { type: "steps", items: [] },
        ],
      },
    ],
  },
  {
    id: "faq",
    title: "Preguntas frecuentes",
    includeInToc: true,
    blocks: [
      {
        type: "subsection",
        title: "¿Copilot reemplaza a mi contador?",
        blocks: [
          { type: "paragraph", text: "No. Copilot te ayuda a leer la situación del negocio y tomar decisiones. Tu contador sigue siendo quien valida, cierra y declara." },
        ],
      },
      {
        type: "subsection",
        title: "¿Por qué Finanzas y Tesorería pueden mostrar números distintos?",
        blocks: [
          { type: "paragraph", text: "Finanzas muestra proyecciones y acumulados históricos. Tesorería muestra la caja operativa que registraste. Son perspectivas distintas del mismo negocio." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué significa Estado: Atención?",
        blocks: [
          { type: "paragraph", text: "Que hay algo para revisar. No es una emergencia, pero conviene leer el detalle y ver si hay acciones pendientes." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué pasa si el sistema contable falla?",
        blocks: [
          { type: "paragraph", text: "Copilot usa los últimos datos disponibles y muestra el problema en Operacional. Los datos anteriores siguen siendo válidos. El sistema se recupera solo cuando la conexión vuelve." },
        ],
      },
      {
        type: "subsection",
        title: "¿Cada cuánto se actualizan los datos?",
        blocks: [
          { type: "paragraph", text: "Los datos críticos (saldos, facturas, recibos) se actualizan automáticamente cada 2 horas." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué significa marcar una alerta como leída?",
        blocks: [
          { type: "paragraph", text: "Que ya la viste. No borra la alerta — queda en el historial para consultarla cuando quieras." },
        ],
      },
      {
        type: "subsection",
        title: "¿Dónde veo quién me debe?",
        blocks: [
          { type: "paragraph", text: "En Cartera (/copilot/cartera) y Clientes (/copilot/clientes)." },
        ],
      },
      {
        type: "subsection",
        title: "¿Dónde veo qué tengo que pagar?",
        blocks: [
          { type: "paragraph", text: "En Tesorería → Pagos (/copilot/tesoreria?section=pagos)." },
        ],
      },
      {
        type: "subsection",
        title: "¿Dónde veo qué hacer primero?",
        blocks: [
          { type: "paragraph", text: "En Acciones (/copilot/acciones)." },
        ],
      },
      {
        type: "subsection",
        title: "¿Dónde veo si los datos están actualizados?",
        blocks: [
          { type: "paragraph", text: "En Operacional (/copilot/operacional)." },
        ],
      },
      {
        type: "subsection",
        title: "¿Los agentes pueden modificar datos?",
        blocks: [
          { type: "paragraph", text: "No. En esta versión solo leen información y sugieren acciones. Vos decidís qué hacer." },
        ],
      },
      {
        type: "subsection",
        title: "¿El agente envía WhatsApp o emails?",
        blocks: [
          { type: "paragraph", text: "No. Puede llevarte al cliente o a la acción correspondiente, pero no envía mensajes automáticamente." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué pasa si Zeta falla y uso el agente?",
        blocks: [
          { type: "paragraph", text: "El agente puede mostrar información con los últimos datos disponibles y recomendar revisar Operacional. No inventa datos nuevos." },
        ],
      },
      {
        type: "subsection",
        title: "Copié o envié un mensaje al cliente. ¿Qué hago ahora?",
        blocks: [
          { type: "paragraph", text: "Si usaste la card Enviar estado de cuenta, Copilot te va a ofrecer el botón Registrar gestión automáticamente. Hacé clic, revisá el pre-llenado (canal y nota) y guardá. Si no usaste esa card, abrí la ficha del cliente, andá a Gestión de cobranza y registrá manualmente: canal, resultado (por ejemplo 'Contactado') y una nota. Eso queda en el historial y lo usan Acciones y Agentes para saber que el cliente ya fue contactado." },
        ],
      },
      {
        type: "subsection",
        title: "¿Registrar una gestión modifica la deuda del cliente?",
        blocks: [
          { type: "paragraph", text: "No. Registrar una gestión es solo un seguimiento operativo. No modifica facturas, saldos ni pagos. Para marcar un pago, hacelo desde el sistema contable (Zeta)." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué pasa si un cliente prometió pagar?",
        blocks: [
          { type: "paragraph", text: "Copilot lo muestra como seguimiento de baja prioridad mientras la fecha no llegó. Si llega la fecha y la deuda sigue abierta, lo muestra como prioridad crítica para que lo verifiques. Registrar una promesa de pago no marca ninguna factura como pagada." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué pasa si cargo una fecha de próximo seguimiento?",
        blocks: [
          { type: "paragraph", text: "Cuando llega ese día, Copilot lo muestra como prioridad alta en los Agentes y en Acciones. Es un recordatorio operativo — no ejecuta ninguna acción automática." },
        ],
      },
      {
        type: "subsection",
        title: "¿Qué es la Agenda de cobranza y cómo la uso?",
        blocks: [
          { type: "paragraph", text: "Es una pestaña dentro de Acciones que agrupa todos los seguimientos, promesas y contactos recientes en un solo lugar. La encontrás en Acciones → pestaña 'Agenda de cobranza', o entrando directo a /copilot/acciones?tab=agenda. También aparece resumida en Hoy: una card con counts de vencidos, hoy, próximos y promesas. Filtrá por categoría y hacé clic en Ver cliente para ir a la ficha. Solo muestra lo que vos registraste — no genera datos ni modifica deuda." },
        ],
      },
    ],
  },
  {
    id: "glosario",
    title: "Glosario — Términos de deuda de clientes",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Referencia rápida de los términos que Copilot usa para describir la deuda de clientes. Cada término tiene un significado preciso para evitar confusión entre saldo, vencimiento y estado." },
    ],
  },
];

export const COPILOT_MANUAL_FIVE_MINUTE_STEPS: string[] = [
  "Abrí Hoy — es la pantalla principal. Muestra caja disponible, deuda de clientes y prioridad del día.",
  "Mirá Acciones — ahí están las cosas concretas que conviene hacer: clientes a llamar, cobros a registrar.",
  "Si hay clientes vencidos → abrí su ficha y contactá por WhatsApp o email directamente desde Copilot.",
  "Si hay pagos próximos → entrá a Tesorería para ver caja real y confirmar que estén cubiertos.",
  "Si querés la foto completa del negocio → Cartera para deuda y antigüedad, Finanzas para panorama general."
];

export const COPILOT_MANUAL_DAILY_FLOW = [] as const;

export const COPILOT_MANUAL_FAQ: Array<{ q: string; a: string }> = [
  {
    "q": "¿Copilot reemplaza a mi contador?",
    "a": "No. Copilot te ayuda a leer la situación del negocio y tomar decisiones. Tu contador sigue siendo quien valida, cierra y declara."
  },
  {
    "q": "¿Por qué Finanzas y Tesorería pueden mostrar números distintos?",
    "a": "Finanzas muestra proyecciones y acumulados históricos. Tesorería muestra la caja operativa que registraste. Son perspectivas distintas del mismo negocio."
  },
  {
    "q": "¿Qué significa Estado: Atención?",
    "a": "Que hay algo para revisar. No es una emergencia, pero conviene leer el detalle y ver si hay acciones pendientes."
  },
  {
    "q": "¿Qué pasa si el sistema contable falla?",
    "a": "Copilot usa los últimos datos disponibles y muestra el problema en Operacional. Los datos anteriores siguen siendo válidos. El sistema se recupera solo cuando la conexión vuelve."
  },
  {
    "q": "¿Cada cuánto se actualizan los datos?",
    "a": "Los datos críticos (saldos, facturas, recibos) se actualizan automáticamente cada 2 horas."
  },
  {
    "q": "¿Qué significa marcar una alerta como leída?",
    "a": "Que ya la viste. No borra la alerta — queda en el historial para consultarla cuando quieras."
  },
  {
    "q": "¿Dónde veo quién me debe?",
    "a": "En Cartera (/copilot/cartera) y Clientes (/copilot/clientes)."
  },
  {
    "q": "¿Dónde veo qué tengo que pagar?",
    "a": "En Tesorería → Pagos (/copilot/tesoreria?section=pagos)."
  },
  {
    "q": "¿Dónde veo qué hacer primero?",
    "a": "En Acciones (/copilot/acciones)."
  },
  {
    "q": "¿Dónde veo si los datos están actualizados?",
    "a": "En Operacional (/copilot/operacional)."
  },
  {
    "q": "¿Los agentes pueden modificar datos?",
    "a": "No. En esta versión solo leen información y sugieren acciones. Vos decidís qué hacer."
  },
  {
    "q": "¿El agente envía WhatsApp o emails?",
    "a": "No. Puede llevarte al cliente o a la acción correspondiente, pero no envía mensajes automáticamente."
  },
  {
    "q": "¿Qué pasa si Zeta falla y uso el agente?",
    "a": "El agente puede mostrar información con los últimos datos disponibles y recomendar revisar Operacional. No inventa datos nuevos."
  },
  {
    "q": "Copié o envié un mensaje al cliente. ¿Qué hago ahora?",
    "a": "Si usaste la card Enviar estado de cuenta, Copilot te va a ofrecer el botón Registrar gestión automáticamente. Hacé clic, revisá el pre-llenado (canal y nota) y guardá. Si no usaste esa card, abrí la ficha del cliente, andá a Gestión de cobranza y registrá manualmente: canal, resultado (por ejemplo 'Contactado') y una nota. Eso queda en el historial y lo usan Acciones y Agentes para saber que el cliente ya fue contactado."
  },
  {
    "q": "¿Registrar una gestión modifica la deuda del cliente?",
    "a": "No. Registrar una gestión es solo un seguimiento operativo. No modifica facturas, saldos ni pagos. Para marcar un pago, hacelo desde el sistema contable (Zeta)."
  },
  {
    "q": "¿Qué pasa si un cliente prometió pagar?",
    "a": "Copilot lo muestra como seguimiento de baja prioridad mientras la fecha no llegó. Si llega la fecha y la deuda sigue abierta, lo muestra como prioridad crítica para que lo verifiques. Registrar una promesa de pago no marca ninguna factura como pagada."
  },
  {
    "q": "¿Qué pasa si cargo una fecha de próximo seguimiento?",
    "a": "Cuando llega ese día, Copilot lo muestra como prioridad alta en los Agentes y en Acciones. Es un recordatorio operativo — no ejecuta ninguna acción automática."
  },
  {
    "q": "¿Qué es la Agenda de cobranza y cómo la uso?",
    "a": "Es una pestaña dentro de Acciones que agrupa todos los seguimientos, promesas y contactos recientes en un solo lugar. La encontrás en Acciones → pestaña 'Agenda de cobranza', o entrando directo a /copilot/acciones?tab=agenda. También aparece resumida en Hoy: una card con counts de vencidos, hoy, próximos y promesas. Filtrá por categoría y hacé clic en Ver cliente para ir a la ficha. Solo muestra lo que vos registraste — no genera datos ni modifica deuda."
  }
];
