 
/** Generated by scripts/generate-copilot-manual-content.mjs ??? do not edit by hand. */
import type { CopilotManualSection } from "./types";

export const COPILOT_MANUAL_GENERATED_SECTIONS: CopilotManualSection[] = [
  {
    id: "copilot",
    title: "?Qu? es Summer87 Copilot?",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Copilot es una pantalla de control para tu negocio. Te ayuda a ver cu?nto dinero hay, qui?n te debe, qu? pagos se vienen, qu? clientes est?n atrasados y qu? acciones conviene hacer primero." },
      { type: "callout", variant: "info", text: "Importante: Copilot no reemplaza a tu contador ni al sistema contable. Es una herramienta para leer la situaci?n del negocio y tomar mejores decisiones." },
      { type: "bullets", items: ["Muestra cu?nto dinero ten?s disponible y qu? pagos est?n programados.","Dice qui?n te debe y cu?nto lleva sin pagar.","Avisa cuando algo importante cambia: un cliente paga, un vencimiento se acerca.","Sugiere qu? hacer primero seg?n la situaci?n del negocio.","Toma los datos de tu sistema contable (Zeta) y los presenta de forma clara."] },
    ],
  },
  {
    id: "navegacion",
    title: "C?mo moverse por Copilot",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El men? lateral est? organizado para que sepas d?nde empezar, d?nde operar y d?nde consultar sin perder rutas ni funciones." },
      { type: "callout", variant: "tip", text: "Acciones vs. Alertas: Alertas cuenta qu? pas?; Acciones dice qu? hacer. Ambas siguen disponibles; Alertas est? en Sistema para no competir con el flujo diario." },
      { type: "bullets", items: ["Hoy ??? operaci?n diaria: prioridad del d?a, caja y cobros urgentes."] },
      { type: "bullets", items: ["Acciones ??? tareas y agenda de cobranza.","Clientes ??? ficha 360, cobranza y contacto.","Cartera ??? deuda por per?odo y reportes.","Tesorer?a ??? caja, pagos pr?ximos y movimientos."] },
      { type: "bullets", items: ["Datos ??? facturas, recibos y registros en tabla.","Reportes ??? cada reporte puede verse en pantalla o descargarse como PDF. Cubre cobranza, caja, ventas, ejecutivo mensual, ranking de clientes y descarga masiva de estados de cuenta.","Panorama financiero ??? lectura general (no reemplaza Tesorer?a ni Cartera).","Agentes IA ??? briefings de lectura; no modifican datos."] },
      { type: "bullets", items: ["Manual de uso ??? esta gu?a.","Alertas ??? qu? pas? en el negocio (inbox de avisos).","Estado del sistema ??? integraciones, sincronizaci?n y salud t?cnica."] },
    ],
  },
  {
    id: "hoy",
    title: "Hoy ??? La pantalla principal",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Hoy es la pantalla de operaci?n diaria. Mirala cada ma?ana para saber qu? resolver primero: caja, cobros urgentes y clientes con deuda vencida." },
      { type: "callout", variant: "tip", text: "Acciones recomendadas ??? hasta 3 pasos con acci?n concreta, impacto esperado y CTA. Usa el mismo motor de prioridades de Hoy; no inventa tareas nuevas." },
      { type: "callout", variant: "info", text: "Fuente y trazabilidad ??? tira compacta bajo el encabezado: Fuente Zeta ? Actualizado hace X horas ? Per?odo mes actual (u otro rango activo)." },
      { type: "callout", variant: "tip", text: "Tu d?a en una frase ??? al entrar, un bloque te dice qu? hacer primero: gestionar clientes con deuda, revisar agenda de cobranza, ir a Tesorer?a o revisar acciones. Un CTA claro para no perderse." },
      { type: "bullets", items: ["Tu d?a en una frase ??? la acci?n concreta sugerida con un CTA (clientes con deuda, agenda, Tesorer?a o acciones).","Estado del d?a (sem?foro) ??? el badge Al d?a / Requiere atenci?n / Atenci?n cr?tica es clicable. Al tocarlo aparece un popover con las se?ales detectadas: clientes que requieren atenci?n, caja post-pagos y m?tricas de cartera. Incluye accesos r?pidos a Clientes, Tesorer?a y Acciones.","Qu? resolver hoy ??? hasta 3 prioridades ejecutivas con t?tulo, motivo y CTA directo: clientes con deuda para gestionar (vencidos y al d?a), agenda de cobranza pendiente y caja ajustada. Solo aparece cuando hay se?ales activas.","Caja disponible ??? dinero en Tesorer?a ahora. No es facturaci?n ni deuda de clientes.","Deuda de clientes ??? Deuda actual (facturas abiertas). Es deuda de clientes, no plata en caja.","Pagos pr?ximos ??? qu? salidas est?n cargadas en Tesorer?a para los pr?ximos d?as.","Caja proyectada ??? cu?nto queda si se pagan todos los compromisos cargados.","Clientes con deuda activa ??? todos los clientes con saldo pendiente, separados por moneda y ordenados por antig?edad de mora. Paginaci?n 25/50/100. Los totales superiores reflejan toda la deuda activa sincronizada desde Zeta.","Detalle financiero del per?odo ??? facturaci?n, cobros y proyecci?n del per?odo seleccionado.","Pr?ximos 30 d?as ??? escenario operativo con caja, pagos y lo que podr?as cobrar.","Generar PDF ??? en Clientes pod?s descargar el reporte de deudores."] },
      { type: "callout", variant: "info", text: "Clientes con deuda ??? la tabla lista todos los deudores con paginaci?n; los totales superiores (Deuda actual UYU/USD) son el rollup completo del negocio, igual que Cartera y Dashboard. Hac? clic en cualquier fila para ver el desglose por factura." },
      { type: "bullets", items: ["Deuda actual ??? saldo abierto del cliente en esa moneda. Viene de las facturas abiertas sincronizadas desde Zeta.","Deuda vencida ??? facturas con vencimiento anterior a hoy (incluye mora de 1 a 30 d?as). Deuda vencida >30 d?as es un subconjunto con m?s de 30 d?as de atraso. Si es 0, el cliente tiene deuda pero todav?a est? dentro del plazo.","Deuda al d?a ??? diferencia entre deuda actual y deuda vencida. Es la parte de la deuda actual todav?a dentro del plazo.","D?as de atraso ??? d?as desde la factura vencida m?s antigua. Aparece solo cuando hay deuda vencida registrada.","Fila expandida ??? hac? clic en una fila para ver el resumen completo: montos, estado (al d?a / requiere seguimiento), fuente del dato, moneda y datos de contacto.","Badge 'Deuda al d?a' ??? el cliente tiene deuda actual pero ninguna factura venci? todav?a.","Badge 'Vencido' ??? hay al menos una factura cuya fecha de vencimiento ya pas?."] },
      { type: "bullets", items: ["Saldo actual cargado ??? el punto de partida. Lo carg?s vos en Tesorer?a con la plata real que ten?s en caja o cuenta.","Cobros Zeta posteriores ??? si un cliente paga despu?s de que cargaste el saldo, Copilot lo suma autom?ticamente cuando aparece en Zeta. No ten?s que registrarlo a mano.","Registros manuales ??? plata que ingresa o egresa pero no viene de Zeta (transferencias, adelantos, pagos realizados). Se registra en Tesorer?a.","Pagos programados sin confirmar ??? no restan hasta que los marc?s como ejecutados."] },
      { type: "bullets", items: ["Si hay clientes con deuda vencida ??? abr? su ficha y contact? por WhatsApp o email.","Si hay pagos pr?ximos ??? entr? a Tesorer?a para confirmar que est?n cubiertos.","Si la caja proyectada queda baja ??? revis? saldo y pagos en Tesorer?a.","Si la caja disponible parece incorrecta ??? verific? que el saldo en Tesorer?a est? actualizado.","Para ver el detalle de facturaci?n y cobros ??? abr? 'Detalle financiero del per?odo'.","Para ver escenario a 30 d?as ??? abr? 'Pr?ximos 30 d?as' dentro del mismo detalle."] },
    ],
  },
  {
    id: "acciones",
    title: "Acciones ??? Qu? hacer primero",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Acciones es la lista de cosas concretas que conviene hacer hoy. No avisa qu? pas? ??? dice qu? hacer." },
      { type: "callout", variant: "tip", text: "Inbox operativo: Prioridades = qu? resolver ? Agenda = a qui?n seguir ? Alertas = qu? revisar (vista previa con enlace al m?dulo completo)." },
      { type: "bullets", items: ["Contactar a un cliente que lleva 45 d?as sin pagar.","Revisar un pago que vence esta semana.","Verificar el estado de la caja antes del cierre del mes."] },
      { type: "bullets", items: ["Todas ??? todo junto.","Cr?ticas ??? las m?s urgentes, las que no pueden esperar.","Cobranza ??? acciones relacionadas con clientes y facturas.","Tesorer?a ??? acciones relacionadas con pagos y caja.","Sistema ??? avisos t?cnicos sobre la sincronizaci?n de datos."] },
      { type: "bullets", items: ["Qu? pas? ??? cada card resume el hecho que la hace prioritaria (deuda, pago, alerta).","Qu? riesgo tiene ??? explica el impacto si no actu?s (caja, cobranza, datos).","Qu? hacer ahora ??? siguiente paso concreto: contactar, confirmar pago, monitorear promesa o registrar resultado.","??ltima gesti?n ??? canal, resultado y fecha de la ?ltima gesti?n registrada.","Prometi? pagar ??? si hay una promesa activa, se muestra la fecha y el monto.","Pr?ximo seguimiento ??? si agendaste un seguimiento, aparece la fecha.","La prioridad puede bajar si el cliente ya fue contactado o tiene una promesa futura.","El bot?n cambia a ?Ver seguimiento? para ir directo al historial del cliente."] },
      { type: "bullets", items: ["Acceso directo: Acciones ? pesta?a Agenda de cobranza (o /copilot/acciones?tab=agenda).","Tambi?n en Hoy: resumen compacto con counts y link Ver agenda.","Vencidos ? seguimientos cuya fecha ya pas?, contactos incorrectos y clientes sin respuesta hace 5+ d?as.","Hoy ? seguimientos programados para hoy. Alta prioridad: hacer antes del cierre del d?a.","Pr?ximos ? seguimientos futuros ordenados por fecha. Para planificar la semana.","Promesas ? clientes con promesa de pago activa, separadas en vencidas (cr?tico) y futuras (monitorear).","Contactados ? clientes contactados en los ?ltimos 7 d?as sin se?al pendiente. Estado 'Esperando respuesta'."] },
    ],
  },
  {
    id: "alertas",
    title: "Alertas ??? Historial de avisos",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Alertas guarda todos los avisos importantes del negocio. Es como la bandeja de entrada, pero para eventos del negocio." },
      { type: "callout", variant: "info", text: "Marcar como le?da solo indica que ya la viste. La alerta sigue ah? para consultarla despu?s." },
      { type: "bullets", items: ["Cobro recibido ??? un cliente pag?.","Cliente vencido ??? un cliente lleva d?as sin pagar.","Pago pr?ximo ??? un pago vence pronto.","Pago vencido ??? un pago ya pas? su fecha.","Problema de sincronizaci?n ??? los datos no se actualizaron correctamente."] },
    ],
  },
  {
    id: "clientes",
    title: "Clientes ??? Directorio y ficha 360",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Clientes muestra a qui?n le vend?s y c?mo est? cada relaci?n comercial. Tocar un cliente abre su ficha 360 con encabezado fijo y pesta?as reales de contenido: Resumen, Cobranza, Estado de cuenta, Facturas, Cobros, Datos y Formas de transferencia." },
      { type: "paragraph", text: "La ficha tiene dos zonas: el encabezado fijo (nombre, RUT, chips de estado, contactos, indicadores y pr?ximo paso) y el contenido de la pesta?a activa. Al cambiar de pesta?a solo se muestra esa secci?n, sin scroll largo por toda la ficha." },
      { type: "paragraph", text: "La barra de pesta?as es sticky, queda anclada al tope al hacer scroll dentro de la pesta?a activa. En mobile las pesta?as se pueden deslizar horizontalmente. La ?ltima pesta?a visitada se recuerda durante la sesi?n." },
      { type: "callout", variant: "tip", text: "Pr?ximo paso ??? debajo de los indicadores, un bloque destacado muestra la acci?n sugerida, la deuda actual y dos botones: Ver estado de cuenta y Generar cobranza." },
      { type: "callout", variant: "tip", text: "Copilot sugiere, vos decid?s. Los res?menes y acciones que muestra la ficha son lecturas autom?ticas. La decisi?n de contactar al cliente, negociar un plazo o dar de baja una deuda siempre es tuya." },
      { type: "bullets", items: ["Encabezado fijo ??? nombre, RUT, c?digo, chips de estado (deuda, riesgo), contactos, indicadores (Deuda UYU/USD, Facturas pendientes, ??ltimo cobro) y Pr?ximo paso.","Pesta?a Resumen ??? lectura del Agente de cliente + ?ltimos 5 movimientos comerciales en formato inline (fecha ? tipo ? importe ? medio) con enlace 'Ver actividad completa'. No muestra cobranza ni estado de cuenta completo.","Pesta?a Cobranza ??? Asistente de cobranza (canal, tono, mensaje, adjuntos sugeridos, WhatsApp y email) + formulario de gesti?n + historial de gestiones. Cada gesti?n del historial tiene botones de editar y eliminar: editar abre un formulario inline para corregir canal, resultado, nota y pr?ximo seguimiento; eliminar pide confirmaci?n antes de borrar.","Pesta?a Estado de cuenta ??? descarga de PDF, env?o de estado de cuenta, deuda actual (UYU y USD) e historial de movimientos. Incluye controles de moneda y rango de fechas.","Pesta?a Facturas ??? tabla completa de facturas emitidas con contador, estado, importe, saldo y fecha.","Pesta?a Cobros ??? tabla completa de cobros registrados con contador, importe, medio de pago, referencia y estado.","Pesta?a Datos ??? tarjeta con los 6 campos de identidad del cliente: Raz?n social, Nombre visible, C?digo, RUT, Email y Tel?fono. Sin secciones colapsables ni informaci?n comercial.","Pesta?a Formas de transferencia ??? gesti?n de aliases de pago: textos, bancos o razones sociales desde donde el cliente suele transferir. Pod?s agregar, editar y eliminar aliases. Se usan para la conciliaci?n autom?tica del extracto bancario Santander."] },
      { type: "bullets", items: ["Deuda actual ??? suma de todas las facturas abiertas (emitidas o pendientes).","Deuda vencida ??? parte de esa deuda cuya fecha de vencimiento ya pas?.","% vencido ??? qu? proporci?n de la deuda actual ya est? vencida. Cuanto m?s alto, m?s urgente."] },
      { type: "bullets", items: ["D?nde generarlo ??? bot?n Generar PDF en Hoy (bloque Clientes cr?ticos) y en Clientes (Cartera de clientes).","Antes de descargar ??? eleg?s moneda, estado, montos m?nimos, antig?edad de vencimiento y contacto.","Vista previa ??? el modal indica cu?ntos clientes entrar?n con los filtros elegidos.","Antig?edad ??? d?as exactos desde la factura vencida m?s antigua (fecha de emisi?n del PDF como referencia).","UYU y USD ??? cada moneda va en filas separadas; los totales no se mezclan.","Columnas ??? cliente, moneda, deuda, vencido, d?as de atraso, contacto y estado.","Orden ??? primero pesos de mayor a menor deuda, luego d?lares de mayor a menor (si aplica el filtro de moneda).","Contacto ??? solo muestra WhatsApp o email si el dato es v?lido (tel?fono corto o email inv?lido no cuenta).","Filtros en el PDF ??? solo aparecen los filtros que realmente restringen el reporte; los valores por defecto no se listan.","Es informativo ??? no modifica datos, no marca clientes como pagados y no env?a mensajes."] },
      { type: "bullets", items: ["Email ??? debajo del encabezado: Enviar email, Copiar email o WhatsApp si el tel?fono es v?lido.","Tel?fono ??? aparece en la franja Contactos, no en una pesta?a aparte.","Si no hay datos de contacto ??? revis? los datos en tu sistema contable (Zeta)."] },
      { type: "bullets", items: ["Qu? pasa ??? resume la situaci?n del cliente: sin deuda, deuda al d?a, vencida o con promesa de pago.","Por qu? importa ??? explica el contexto: cu?nto tiene vencido, en qu? moneda.","Qu? hacer ahora ??? sugiere el pr?ximo paso: preparar cobranza, ver seguimiento o revisar estado de cuenta.","Insights ??? se?ales operativas (vencido, promesa, ?ltima gesti?n). No incluye contacto ni ?ltimo movimiento porque ya est?n arriba.","CTA ??? el bot?n lleva al asistente de cobranza, al estado de cuenta o al seguimiento.","No modifica nada. No marca facturas. No env?a mensajes. Solo sugiere."] },
      { type: "bullets", items: ["Canal ??? elige WhatsApp o Email seg?n como prefer?s contactar al cliente.","Tono ??? Amable para el primer aviso, Firme si ya pas? un tiempo, Urgente si la deuda lleva mucho sin atenderse.","Generar mensaje ??? crea el texto con los datos reales del cliente (nombre y monto).","Adjuntos sugeridos ??? seg?n la deuda por moneda, Copilot muestra links para descargar Estado de cuenta UYU y/o USD. Si debe en una sola moneda, aparece solo ese PDF.","WhatsApp ??? no adjunta archivos autom?ticamente: descarg? el PDF y adjuntalo manualmente al enviar el mensaje.","Email ??? abre tu cliente de correo con asunto y cuerpo; descarg? y adjunt? el PDF antes de enviar.","Copiar mensaje ??? copia el texto al portapapeles para pegarlo donde quieras.","Enviar email ??? si el cliente tiene email cargado, abre tu cliente de correo con el texto y asunto preparados.","Abrir WhatsApp ??? aparece solo si el cliente tiene un celular utilizable (formato uruguayo). Al hacer clic, abre WhatsApp con el mensaje ya escrito.","Tel?fono no utilizable para WhatsApp ??? aparece cuando hay un tel?fono cargado pero es fijo o tiene formato inv?lido. Correg? el tel?fono en Zeta para habilitarlo.","Sin tel?fono cargado ??? el cliente no tiene tel?fono registrado en el sistema."] },
      { type: "bullets", items: ["Canal ??? eleg?s c?mo fue el contacto: WhatsApp, Email, Tel?fono u Otro.","Resultado ??? qu? pas?: Contactado, Prometi? pagar, Sin respuesta, Contacto incorrecto, En disputa, Requiere seguimiento.","Nota ??? campo libre para escribir el detalle: 'prometi? pagar el viernes', 'sin respuesta, llamar en 3 d?as', etc.","Pr?ximo seguimiento ??? fecha opcional para recordar cu?ndo volver a contactar.","Promesa de pago ??? si el resultado fue 'Prometi? pagar', la fecha es requerida para guardar la gesti?n. El monto es opcional.","Registrar gesti?n ??? guarda el registro. No modifica la deuda ni marca facturas como pagadas."] },
      { type: "bullets", items: ["Contactado ??? lograste comunicarte con el cliente.","Prometi? pagar ??? el cliente se compromete a pagar en una fecha. La fecha de promesa es requerida; el monto es opcional.","Sin respuesta ??? llamaste o escribiste pero no contest?.","Contacto incorrecto ??? el n?mero o email que ten?s no es el correcto.","En disputa ??? el cliente no reconoce la deuda o la cuestiona.","Requiere seguimiento ??? necesit?s volver a contactar, pero no hay m?s detalle por ahora."] },
      { type: "bullets", items: ["Registrar una gesti?n hace que Acciones y Agentes reconozcan el estado real del cliente, sin repetir la misma recomendaci?n de contacto.","Si el cliente fue contactado recientemente, Copilot lo muestra como 'ya contactado' o 'esperando respuesta' en lugar de 'priorizar cobranza'.","Si hay una promesa de pago futura, los Agentes sugieren monitorearla en lugar de contactar.","Si la promesa vence sin confirmaci?n de pago, la prioridad sube autom?ticamente.","Si el resultado fue 'Sin respuesta' hace m?s de 5 d?as, vuelve a ser prioritario.","Si el resultado fue 'Contacto incorrecto', la prioridad se mantiene alta porque no hubo contacto ?til.","La deuda nunca desaparece. Solo cambia el copy y el tono de la recomendaci?n."] },
      { type: "bullets", items: ["Bot?n Descargar PDF ??? aparece en la secci?n Estado de cuenta hist?rico de la ficha.","Incluye todos los movimientos del cliente: facturas emitidas, cobros recibidos y saldo acumulado.","Cada factura muestra su concepto/?tem real (viene de Zeta) debajo del movimiento principal.","Cada recibo muestra la caja o medio de cobro como l?nea secundaria.","Las facturas con ajuste van en columna Haber (descuentan saldo), no como deuda a cobrar.","Separa UYU y USD en bloques independientes. No mezcla monedas.","Usa el modo ledger: incluye tambi?n registros archivados para un historial completo.","El PDF no modifica datos ??? es solo lectura de lo sincronizado desde Zeta.","El archivo se descarga directamente en el navegador."] },
      { type: "bullets", items: ["Eleg? el canal: Email o WhatsApp.","Eleg? la moneda del mensaje: Pesos (UYU) o D?lares (USD) ??? el saldo del texto se ajusta autom?ticamente.","Adjuntos sugeridos ??? Copilot ofrece descargar Estado de cuenta UYU y/o USD seg?n la deuda real del cliente (no seg?n la moneda del mensaje).","Eleg? el tono: Amable (informal), Firme (formal exigente) o Breve (mensaje corto).","El mensaje se genera con el per?odo del a?o actual al d?a de hoy y el saldo vigente del cliente.","Bot?n Copiar mensaje ??? copia el texto al portapapeles.","Bot?n Abrir email ??? abre el cliente de correo con destinatario, asunto y cuerpo pre-cargados.","Bot?n Abrir WhatsApp ??? abre WhatsApp Web o la app con el mensaje pre-cargado.","Si el cliente no tiene email registrado, el bot?n de email queda deshabilitado.","Si el cliente no tiene celular apto para WhatsApp, ese bot?n queda deshabilitado.","Los PDFs no se adjuntan autom?ticamente ??? descargalos desde Adjuntos sugeridos y adjuntalos manualmente antes de enviar.","Despu?s de Copiar, Abrir email o Abrir WhatsApp, aparece el bot?n Registrar gesti?n. Al hacerlo, el formulario de Gesti?n de cobranza se completa autom?ticamente con el canal y una nota del per?odo enviado.","Si el formulario de cobranza ya tiene texto, en lugar de pisarlo aparece una sugerencia que pod?s aplicar o ignorar."] },
      { type: "bullets", items: ["Buscador ??? busca en texto libre: cliente, n?mero, RUT, concepto, m?todo de cobro o estado.","Listado ??? altern?s entre Activos, Inactivos o Todos sin recargar la p?gina.","Contador ??? muestra cu?ntos registros coinciden con los filtros activos.","Per?odo (Facturas y Recibos) ??? filtr? por Mes y a?o, Rango de fechas o Todo. Botones r?pidos: Mes actual, Hoy (Recibos) y Limpiar.","Chips Facturas ??? Todos / Con saldo / Ajustes y Pesos / D?lares.","Chips Recibos ??? Pesos / D?lares.","Al hacer clic en cualquier registro se abre el panel lateral con el detalle completo.","Los IDs t?cnicos de Zeta quedan en el bloque ?Datos t?cnicos? dentro del panel ??? no aparecen en la vista principal."] },
      { type: "bullets", items: ["Datos ??? panel lateral r?pido: c?digo, deuda, facturas y contactos b?sicos.","Ficha completa (esta secci?n) ??? pesta?as reales con contenido separado. Cada pesta?a muestra solo su informaci?n sin scroll por toda la ficha.","Detalle t?cnico ??? secci?n colapsada dentro de la pesta?a Datos. Solo para casos avanzados."] },
      { type: "bullets", items: ["Formas de transferencia ??? pod?s registrar uno o m?s textos que identifican c?mo transfiere ese cliente (por ejemplo: 'DOLBY SOCIEDAD ANONIMA', 'ACME SA', 'PETROVIC SOLUTIONS').","Agreg? desde la ficha del cliente: secci?n ?Formas de transferencia? ??? bot?n Agregar.","Cada alias tiene un campo de texto obligatorio (3-300 caracteres) y una nota opcional.","Pod?s editar o eliminar cualquier alias en cualquier momento.","Si elimin?s un alias, Copilot deja de usarlo para la conciliaci?n Santander a partir del siguiente import.","La b?squeda en la lista de clientes incluye aliases: si busc?s 'DOLBY', aparecen los clientes con ese alias aunque el nombre del cliente sea otro.","Si el cliente no tiene aliases pero tiene una forma de transferencia cargada en el sistema anterior, aparece como sugerencia en el estado vac?o para que la migr?s con el bot?n Agregar.","Permisos ??? solo usuarios con rol de escritura pueden agregar, editar o eliminar aliases. Usuarios de solo lectura ven la lista pero no pueden modificarla."] },
      { type: "glossary", entries: [{"term":"Factura emitida","definition":"Se emiti? pero a?n no fue pagada ni venci?."},{"term":"Factura vencida","definition":"Pas? su fecha de vencimiento sin cobro registrado."},{"term":"Factura pagada","definition":"Hay un cobro registrado que la cubre."},{"term":"Cobro registrado","definition":"Pago que el cliente realiz?, registrado en el sistema contable."}] },
    ],
  },
  {
    id: "cartera",
    title: "Cartera ??? Qui?n te debe y cu?nto",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Cartera muestra el dinero que los clientes te deben. Es la vista de cobranza: cu?nto hay pendiente, qu? est? vencido y qui?nes tienen m?s urgencia." },
      { type: "callout", variant: "info", text: "Cartera ??? Caja. Lo que ves en Cartera es deuda que los clientes todav?a no pagaron. No es plata disponible. Entra en caja solo cuando el cliente paga y el cobro aparece en Zeta. El Dinero disponible viene de Tesorer?a, no de Cartera." },
      { type: "glossary", entries: [{"term":"Al d?a","definition":"Facturas que a?n no vencieron."},{"term":"1 a 30 d?as","definition":"Reci?n vencido. Conviene avisar."},{"term":"31 a 60 d?as","definition":"Ya lleva un mes. Priorizar el contacto."},{"term":"61 a 90 d?as","definition":"Problema real. Gesti?n urgente."},{"term":"M?s de 90 d?as","definition":"Muy dif?cil de cobrar. Acci?n inmediata."}] },
    ],
  },
  {
    id: "tesoreria",
    title: "Tesorer?a ??? Caja, pagos y compromisos",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Tesorer?a es donde carg?s y gestion?s el dinero operativo: el saldo actual de caja, los egresos y pagos que no vienen de Zeta. Es la fuente del n?mero Dinero disponible que ves en Hoy." },
      { type: "bullets", items: ["No es facturaci?n anual. No es lo que te deben. No es el total cobrado hist?rico.","Es el punto de partida: la plata que ten?s ahora, que vos conoc?s mejor que nadie.","Se carga en Tesorer?a ??? panel de caja disponible ??? bot?n Editar saldo actual.","Pod?s actualizarlo cuando quieras. Cada vez que lo actualiz?s, la fecha de corte se resetea a ese d?a.","UYU y USD se cargan por separado."] },
      { type: "bullets", items: ["Si un cliente paga despu?s de que cargaste el saldo, el cobro aparece en Zeta y Copilot lo suma solo al Dinero disponible.","Si el cobro ocurri? antes de la fecha en que cargaste el saldo, no se suma de nuevo ??? ya estaba incluido en el saldo que cargaste.","Esto evita duplicar: el saldo que cargaste ya refleja todo lo cobrado hasta ese momento.","Los cobros anulados o cancelados no suman aunque tengan fecha posterior."] },
      { type: "bullets", items: ["Registr? en Tesorer?a los pagos que hac?s: sueldos, impuestos, proveedores, gastos operativos.","Los egresos confirmados restan del Dinero disponible desde la fecha en que ocurrieron.","Los pagos programados (fecha futura o sin confirmar) no restan hasta que los ejecut?s.","Los ingresos manuales (no de facturas Zeta) tambi?n se registran ac? y suman al disponible.","Caja manual ??? Movimientos de entrada y salida registrados por vos."] },
      { type: "bullets", items: ["Soporta CSV, Excel y PDF Santander con texto extra?ble. PDF no usa OCR. El importador reconoce el extracto por la estructura de la tabla aunque el logo Santander no sea texto extra?ble.","Usuario y modo demo pueden generar vista previa (no persiste datos). Guardar o importar el extracto requiere superadmin.","Gener? un preview antes de guardar: ves fecha, monto, tipo y un estado de coincidencia por fila.","Coincide ??? el movimiento del banco parece ya estar en Tesorer?a (y en Zeta si aplica).","Falta en Copilot ??? hay se?al en Zeta o es un cobro en banco sin movimiento equivalente en Tesorer?a.","Falta en Zeta ??? est? en Tesorer?a pero no hay recibo Zeta en la ventana de fechas.","Posible coincidencia ??? monto, fecha o texto parecen relacionados; conviene revisar manualmente.","Cliente sugerido por forma de transferencia ??? Copilot detect? que la descripci?n del movimiento contiene el texto de una de las formas de transferencia registradas para ese cliente. Conviene validar antes de confirmar.","Las formas de transferencia se configuran en la ficha de cada cliente (secci?n Formas de transferencia). Pod?s registrar varios aliases por cliente.","Si el PDF no puede leerse, export? CSV o Excel desde Santander.","No modifica caja autom?ticamente ni crea recibos en Zeta. Guardar solo almacena el extracto para conciliaci?n.","Para impactar caja ten?s que crear o confirmar un movimiento de Tesorer?a por separado."] },
      { type: "bullets", items: ["Caja ??? saldo disponible cargado al corte. Arriba del formulario: ?Qu? quer?s registrar? (Ingreso, Egreso o Pago programado).","Pagos pr?ximos ??? resumen UYU/USD (30 d?as), lista de pr?ximos pagos, recurrentes e historial. Un solo bot?n principal ?+ Nuevo pago?; recurrentes con ?+ Nuevo recurrente?. No afectan caja hasta confirmarse.","Movimientos ??? ingresos y egresos confirmados que ajustan tu caja. Incluye importador bancario (extracto CSV/XLSX) y control contable.","Cobranza del mes ??? recibos cobrados en el per?odo seleccionado, filtrable por fecha y moneda. Solo lectura desde Zeta."] },
      { type: "bullets", items: ["Pagos pr?ximos ??? orden de la pantalla: (1) resumen UYU/USD pr?ximos 30 d?as, (2) tabla de pr?ximos pagos con ?+ Nuevo pago?, (3) recurrentes con ?+ Nuevo recurrente?, (4) historial de pagados/cancelados.","Formularios unificados ??? al crear o editar un pago us?s los mismos campos: Concepto, Categor?a, Moneda, Monto y Vencimiento.","Recurrentes ??? Copilot genera autom?ticamente cada vencimiento en la lista de pr?ximos pagos. Pausar no borra historial.","Confirmar pago ??? desde la tabla pod?s marcar un pago como ejecutado; opcionalmente registra el egreso en caja."] },
      { type: "bullets", items: ["Control contable de movimientos ??? en la secci?n Movimientos, cada l?nea tiene columnas Contabilizado, Asiento Zeta y Coincidencia.","Contabilizado ??? marc? el movimiento como contabilizado en el sistema contable usando el bot?n (palomita/cruz).","Asiento Zeta ??? n?mero y fecha del asiento Zeta correspondiente, si fue cargado manualmente.","Coincidencia ??? estado de la validaci?n: Pendiente (sin asiento cargado), Coincide (monto y moneda iguales), Mismatch (diferencias), Requiere revisi?n o Confirmado manualmente."] },
      { type: "bullets", items: ["Filtros contables en Movimientos ??? botones r?pidos para ver solo: Todos, Sin contabilizar, Contabilizados, Coincide, No coincide, Requiere revisi?n.","Para marcar como contabilizado: hac? clic en el icono de palomita. Para desmarcar: volv? a hacer clic.","El estado de coincidencia es informativo. Copilot no modifica datos en Zeta."] },
      { type: "bullets", items: ["No marca ninguna factura como pagada desde Tesorer?a.","No modifica datos en Zeta.","No duplica cobros: si el cobro es anterior al saldo cargado, no se suma de nuevo.","UYU y USD se calculan por separado ??? no se mezclan.","Los cobros de clientes vienen de Zeta; los egresos operativos se registran en Tesorer?a."] },
      { type: "callout", variant: "tip", text: "Tipo de cambio (TC) ??? se configura desde Dashboard Resumen al seleccionar 'USD consolidado'. El chip '1 USD = X UYU' y el bot?n 'Editar TC' solo aparecen en ese modo. No se configura desde Tesorer?a." },
    ],
  },
  {
    id: "finanzas",
    title: "Panorama financiero ??? Lectura ejecutiva",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Panorama financiero es el panel ejecutivo para CEO y contador: ventas, cobros, deuda, caja y evoluci?n del negocio. No reemplaza Cartera ni Tesorer?a para operar el d?a a d?a ni es un cierre contable formal." },
      { type: "callout", variant: "info", text: "Si el mes actual est? en curso, Finanzas no presenta ???este mes vs el anterior??? como comparaci?n principal de performance: muestra el acumulado parcial y compara meses cerrados (ej. Mayo vs Abril). Para cierre contable formal, valid? con tu contador." },
      { type: "bullets", items: ["Fecha de corte ??? d?a hasta el cual est?n calculados los n?meros (hoy operativo).","Per?odo actual ??? desde el 1.? del mes hasta la fecha de corte (mes en curso, lectura parcial).","??ltimo mes cerrado ??? mes calendario completo anterior; Finanzas lo usa para comparar desempe?o mensual cuando el mes actual reci?n empieza.","Vista por capas ??? resumen ejecutivo (6 m?tricas), comparaci?n principal, evoluci?n, riesgo de cobranza y proyecci?n visibles; detalle avanzado colapsado.","Resumen ejecutivo ??? hasta 6 KPIs combinando UYU y USD, con 3 bullets de lectura integrados.","Comparaci?n principal ??? una tabla por moneda (selector UYU/USD): ?ltimo mes cerrado vs anterior; el mes en curso aparece como nota aparte.","Ventas ??? facturas del per?odo. Fuente distinta a cobros y a deuda.","Cobros ??? recibos por fecha de recibo; pueden superar ventas del per?odo si se recupera deuda anterior.","Deuda actual y vencida ??? saldo de clientes en Cartera al corte; no es lo mismo que cobros ni caja.","Caja disponible ??? Tesorer?a (baseline + movimientos); no es facturaci?n ni cierre bancario.","Proyecci?n 30 d?as ??? estimaci?n operativa compacta (caja + cobros esperados ??? pagos cargados).","Riesgo de cobranza ??? un bloque con selector UYU/USD (deuda, vencido, top 5).","Detalle avanzado ??? colapsado: clientes, desglose contable, semana vs semana y enlace fiscal.","Evoluci?n comercial ??? gr?fico principal (6 meses por defecto); tabla colapsada ?Ver tabla de evoluci?n?.","Obligaciones fiscales ??? al final de la p?gina, fuera del detalle avanzado."] },
    ],
  },
  {
    id: "datos",
    title: "Datos ??? Consulta de registros base",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Datos es una vista de consulta y auditor?a de registros sincronizados desde Zeta. Pod?s ver clientes, facturas, recibos, pagos y obligaciones fiscales." },
      { type: "callout", variant: "tip", text: "Estados vac?os ??? cada tabla (clientes, facturas, recibos, etc.) explica por qu? no hay registros, qu? filtro probar y qu? aparecer? cuando haya datos sincronizados." },
      { type: "callout", variant: "info", text: "Datos es solo para consultar y verificar. Para gesti?n diaria us? Cartera, Tesorer?a o Acciones." },
      { type: "bullets", items: [
        "Clientes ??? directorio completo con datos de contacto.",
        "Facturas ??? todas las facturas por per?odo, con saldo y estado. Filtros: per?odo, moneda, estado de pago (Vencidas / Pagadas / Con saldo / Todas) y cliente.",
        "Recibos ??? cobros registrados con n?mero, cliente, monto, moneda y m?todo. Filtros: per?odo, moneda y cliente.",
        "Pagos ??? pagos fiscales y a proveedores. Filtro de fecha (rango desde/hasta). Solo lectura: los pagos no se pueden crear, editar ni borrar desde Datos.",
        "Obligaciones fiscales ??? vencimientos tributarios. Filtro de fecha de vencimiento (rango desde/hasta).",
      ] },
      { type: "callout", variant: "warning", text: "Pagos es solo lectura en esta secci?n. Para crear, editar o borrar pagos, us? Tesorer?a ??? Pagos pr?ximos." },
      { type: "paragraph", text: "Si una factura o recibo no muestra moneda (aparece '? sin moneda'), significa que el registro no tiene currency_code registrado. No es un error del sistema: indica que ese dato no lleg? desde Zeta. Pod?s revisarlo directamente en tu sistema contable." },
      { type: "paragraph", text: "Algunos recibos muestran '? vinculaci?n no disponible (Zeta)' en lugar del n?mero de factura. Esto es normal: Zeta no expone el v?nculo recibo ??? factura en su API de cobranzas. El recibo es v?lido; solo no tiene la referencia de factura disponible." },
      { type: "paragraph", text: "Si busc?s un cliente inactivo (archivado) en Datos, pod?s abrir su ficha completa. La ficha se abre normalmente pero con un aviso amarillo que indica que el cliente est? inactivo. Todos los datos hist?ricos se muestran en modo lectura." },
      { type: "bullets", items: [
        "Datos ??? consulta r?pida: c?digo, RUT, tel?fono, deuda actual y facturas recientes.",
        "Al tocar un cliente aparece un panel lateral con deuda, facturas, recibos y contactos.",
        "Ver ficha completa ??? funciona tambi?n para clientes inactivos (muestra banner de estado).",
        "Si solo quer?s confirmar un dato, us? el panel lateral. Si vas a gestionar al cliente, abr? la ficha completa.",
      ] },
    ],
  },
  {
    id: "agentes",
    title: "Agentes IA ??? Pr?ximamente",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "La pantalla Agentes IA est? en preparaci?n. Todav?a no ejecuta an?lisis coordinado ni modifica datos." },
      { type: "callout", variant: "info", text: "Hoy y Acciones ya muestran prioridades con los datos actuales. Los agentes sumar?n res?menes coordinados cuando est?n disponibles." },
      { type: "bullets", items: ["Qu? har?n ??? leer deuda, caja, cobranza y alertas para ordenar el d?a en lenguaje claro.","C?mo ayudar?n ??? priorizar clientes, pagos y revisiones de caja con explicaci?n del impacto esperado.","Cu?ndo ver?s datos ??? cuando haya movimiento comercial sincronizado, igual que en Hoy y Dashboard.","Qu? no hacen ??? no pagan, no borran, no env?an mensajes autom?ticamente. Vos decid?s cada paso."] },
      { type: "bullets", items: ["Mientras tanto ??? us? Hoy para operaci?n diaria y Acciones para tareas concretas.","Dashboard Resumen ??? an?lisis ejecutivo del negocio.","Clientes 360 ??? ficha y cobranza por cliente."] },
    ],
  },
  {
    id: "reportes",
    title: "Reportes ??? vista en pantalla y PDF",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Reportes centraliza los 6 reportes operativos, organizados en tres grupos: Cobranza, Finanzas y Clientes. Cada reporte tiene dos modos de uso:" },
      { type: "bullets", items: ["Ver reporte ??? abre una vista previa dentro de Copilot con filtros, resumen de m?tricas y tabla. Ideal para consulta r?pida sin descargar nada.","Generar PDF ??? descarga el reporte como archivo profesional para enviar, imprimir o archivar.","Ambos modos usan los mismos datos y c?lculos. No hay diferencia en los n?meros."] },
      { type: "bullets", items: ["Deudores ??? clientes con deuda, moneda, antig?edad y contacto. Los filtros se aplican en tiempo real en la vista previa. Cuando el filtro de moneda es 'UYU + USD', el PDF separa los clientes en dos secciones (Pesos y D?lares) sin mezclar monedas.","Cobranza mensual ??? cobros registrados del mes por moneda. Incluye fecha, n?mero de recibo, cliente e importe.","Caja mensual ??? movimientos del per?odo con saldo inicial, ingresos, egresos y saldo acumulado. Ingresos en verde, egresos en rojo.","Ventas ??? detalle de facturas del per?odo por moneda (fecha, n?mero, cliente e importe), con deduplicaci?n de comprobantes Zeta y total al pie.","Ejecutivo mensual ??? resumen CEO: indicadores clave, top 5 clientes, top 5 deudores, estado de caja y nivel de riesgo (Bajo / Atenci?n / Cr?tico).","Dashboard Resumen Ejecutivo ??? PDF del Dashboard por per?odo personalizado: estado financiero (Estable/Atenci?n/Cr?tico), tabla de 6 KPIs, tendencia mensual, deuda por antig?edad (4 buckets), top 10 deudores, top 10 facturaci?n, estado de cartera, tabla completa de clientes con deuda activa y movimientos del per?odo (m?x. 30). Seleccion?s per?odo (desde/hasta) y moneda (UYU, USD o ambas).","Clientes principales ??? ranking ordenable por facturaci?n, deuda total o deuda vencida. Muestra participaci?n y nivel de riesgo por cliente.","Estado de cuenta por cliente ??? vista previa sin filtro de mes/a?o: muestra saldos vigentes desde 2026 y selector de moneda (Pesos, D?lares o UYU + USD). El PDF respeta la moneda elegida. Si super?s el l?mite de descargas, ver?s: ?Demasiadas descargas. Esper? unos segundos e intent? de nuevo.?","Estado de cuenta individual ??? se genera desde la ficha de cada cliente (pesta?a Estado de cuenta).","Los reportes son de solo lectura: no modifican facturas, caja ni gestiones.","Nunca se suman UYU + USD entre s?: cada moneda tiene su propia secci?n en el PDF, sin conversi?n ni combinaci?n."] },
    ],
  },
  {
    id: "operacional",
    title: "Estado del sistema ??? Sincronizaci?n y salud t?cnica",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Estado del sistema (antes Operacional) muestra si los datos se est?n actualizando correctamente y la salud de la integraci?n con Zeta." },
      { type: "callout", variant: "info", text: "Al entrar ver?s Confianza del dato: ?ltima actualizaci?n, cantidad de clientes/facturas/recibos sincronizados y si hay conflictos." },
      { type: "bullets", items: ["Cu?ndo fue la ?ltima actualizaci?n de datos.","Si la conexi?n con el sistema contable est? funcionando.","Cu?ntas actualizaciones salieron bien y cu?ntas fallaron.","El estado general de los flujos de datos."] },
    ],
  },
  {
    id: "estado",
    title: "Estado: Atenci?n / Estable / Cr?tico",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El estado del negocio aparece en la parte superior de la pantalla y en algunas p?ginas como Hoy y Operacional. Te indica de un vistazo si todo est? bien o si hay algo para atender." },
      { type: "callout", variant: "tip", text: "Al tocar o hacer clic sobre el estado se despliega el detalle: qu? alertas est?n activas, cu?les son cr?ticas y cu?les son solo informativas." },
      { type: "status", entries: [{"level":"ok","title":"Estable","description":"Todo est? dentro de lo esperado. Pod?s operar con normalidad."},{"level":"warning","title":"Atenci?n","description":"Hay algo para revisar. No es urgente, pero conviene no ignorarlo. Tocar el estado muestra el detalle."},{"level":"critical","title":"Cr?tico","description":"Hay algo importante que puede afectar caja, pagos o la calidad de los datos. Revisarlo pronto."}] },
    ],
  },
  {
    id: "campana",
    title: "Campana de notificaciones",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "La campana aparece en la parte superior de la pantalla. Cuando tiene un n?mero rojo, significa que hay novedades sin leer." },
      { type: "bullets", items: ["Un cliente pag? una factura.","Un cliente qued? con deuda vencida.","Un pago importante vence pronto.","Un pago ya pas? su fecha sin registrarse.","Hubo un problema en la actualizaci?n de datos."] },
      { type: "bullets", items: ["Tocar el bot?n de la campana abre el panel de notificaciones.","Cada notificaci?n tiene un link para ir directo al detalle.","?Marcar todas como le?das? quita el n?mero rojo ??? no borra las notificaciones.","?Ver todas? lleva al listado completo en Alertas."] },
    ],
  },
  {
    id: "problemas",
    title: "?Qu? hacer si algo aparece en rojo?",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Ver algo en rojo no significa que el negocio est? en crisis. Puede ser una alerta importante o simplemente un dato para revisar." },
    ],
  },
  {
    id: "roles-permisos",
    title: "Roles y permisos",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Copilot tiene dos roles principales: Superadmin y Usuario. El acceso detallado a cada m?dulo se configura con permisos Ver y Modificar desde el Panel administrativo." },
      { type: "roles", entries: [{"role":"superadmin","label":"Superadmin","description":"Acceso total. Puede leer y modificar cualquier dato de la empresa. El ?nico que puede administrar usuarios, roles y permisos."},{"role":"usuario","label":"Usuario","description":"Rol base. El acceso a cada m?dulo se define individualmente con los permisos Ver y Modificar. Por defecto: solo lectura en todo."}] },
      { type: "callout", variant: "info", text: "Los permisos se configuran por m?dulo desde el Panel administrativo (solo superadmin). Ver da acceso de lectura; Modificar da acceso de escritura e incluye Ver autom?ticamente. Sin ninguno de los dos, el m?dulo no aparece en el men?." },
      { type: "bullets", items: ["Navegar por todas las secciones permitidas seg?n rol y permisos.","Ver dashboards, fichas de clientes, movimientos y deuda (donde haya acceso de lectura).","Abrir reportes en pantalla y descargar PDFs ??? son operaciones de lectura.","Generar vista previa del importador Santander ??? no guarda ni modifica caja.","Consultar alertas, notificaciones y Agentes IA."] },
      { type: "bullets", items: ["Cargar ingresos, egresos o ajustes en Tesorer?a (requiere permiso Modificar en Tesorer?a o superadmin).","Registrar gestiones de cobranza (requiere permiso Modificar en Acciones o superadmin).","Ejecutar sincronizaciones manuales (solo superadmin).","Crear, editar o eliminar usuarios (solo superadmin v?a Panel administrativo).","Acceder al Panel administrativo (solo superadmin)."] },
      { type: "bullets", items: ["Reporte de deudores.","Cobranza mensual.","Caja mensual.","Ventas.","Ejecutivo mensual.","Clientes principales.","Estado de cuenta masivo (desde Reportes, por moneda).","Estado de cuenta individual (desde la ficha de cada cliente)."] },
    ],
  },
  {
    id: "admin",
    title: "Panel administrativo",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El Panel administrativo es exclusivo del superadmin. Permite crear usuarios, asignar roles y configurar qu? puede ver y modificar cada persona en la empresa." },
      { type: "callout", variant: "warning", text: "Solo superadmin puede acceder a /copilot/admin. Cualquier otro usuario que intente entrar es redirigido a Hoy." },
      {
        type: "subsection",
        title: "C?mo crear un usuario",
        blocks: [
          { type: "steps", items: ["Ir a Panel administrativo ??? Nuevo usuario.","Ingresar email, nombre completo y rol (Superadmin o Usuario).","Indicar un PIN temporal o dejarlo vac?o para que se genere autom?ticamente.","Hacer clic en Crear usuario.","El PIN temporal se muestra UNA SOLA VEZ ??? anotarlo y entregarlo al usuario de forma segura.","El usuario puede cambiar su PIN luego desde el perfil (si aplica) o el superadmin puede resetearlo."] },
        ],
      },
      {
        type: "subsection",
        title: "Roles disponibles",
        blocks: [
          { type: "bullets", items: ["Superadmin ??? acceso total a todos los m?dulos. Puede gestionar usuarios, roles y permisos. El ?nico que accede al Panel administrativo.","Usuario ??? rol base de solo lectura. Puede navegar, consultar y descargar reportes. No puede modificar datos operativos."] },
        ],
      },
      {
        type: "subsection",
        title: "Qu? significa cada nivel de acceso",
        blocks: [
          { type: "bullets", items: ["Sin acceso ??? el m?dulo desaparece del men? lateral y la URL queda bloqueada. Si el usuario intenta entrar manualmente, el sistema lo redirige a Hoy o muestra un mensaje de acceso denegado.","Ver ??? puede navegar, ver datos y descargar PDFs del m?dulo.","Modificar ??? puede leer y tambi?n crear, editar o eliminar registros en ese m?dulo. Marcar Modificar activa Ver autom?ticamente."] },
        ],
      },
      {
        type: "subsection",
        title: "C?mo editar permisos de un usuario",
        blocks: [
          { type: "steps", items: ["En la tabla de usuarios, hacer clic en el ?cono de l?piz (Editar permisos).","Se abre un modal con la tabla de m?dulos.","Marcar Ver para dar acceso de lectura a un m?dulo. Marcar Modificar para dar acceso de escritura (incluye Ver autom?ticamente). Desmarcar Ver quita ambos accesos.","Hacer clic en Guardar cambios.","Los cambios aplican en el pr?ximo acceso del usuario (o inmediatamente si recarga la p?gina)."] },
        ],
      },
      {
        type: "subsection",
        title: "C?mo resetear el PIN de un usuario",
        blocks: [
          { type: "steps", items: ["En la tabla de usuarios, hacer clic en el ?cono de llave (Resetear PIN).","Confirmar la acci?n en el popup.","El nuevo PIN temporal se muestra una sola vez.","La sesi?n activa del usuario se invalida autom?ticamente."] },
        ],
      },
      {
        type: "subsection",
        title: "C?mo eliminar un usuario",
        blocks: [
          { type: "steps", items: ["En la tabla de usuarios, hacer clic en el ?cono de papelera (Eliminar usuario).","Se abre un modal de confirmaci?n.","Escribir ELIMINAR para confirmar.","Hacer clic en Eliminar usuario.","El usuario pierde acceso inmediatamente. Esta acci?n no se puede deshacer desde la interfaz."] },
          { type: "callout", variant: "warning", text: "No se puede eliminar el ?nico superadmin activo. El sistema lo bloquea para proteger el acceso administrativo." },
        ],
      },
      {
        type: "subsection",
        title: "Recomendaciones de seguridad",
        blocks: [
          { type: "bullets", items: ["No compartir la cuenta superadmin entre varias personas.","Crear una cuenta separada para cada persona del equipo.","Mantener siempre al menos un superadmin activo (el sistema lo bloquea si intent?s eliminar el ?ltimo).","El PIN temporal que se muestra al crear o resetear un usuario debe entregarse en forma segura (no por email sin encriptar).","Revisar peri?dicamente la lista de usuarios activos y eliminar accesos que ya no correspondan."] },
        ],
      },
    ],
  },
  {
    id: "inicio-sesion",
    title: "Inicio de sesi?n",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "El acceso a Copilot es con usuario y PIN en la pantalla de login. No usa enlaces externos ni registro p?blico." },
      { type: "steps", items: ["Ir a /login.","Ingresar Usuario y PIN provistos por quien administra la empresa.","Pulsar Entrar.","Si las credenciales son v?lidas, Copilot redirige a /copilot/hoy."] },
      { type: "bullets", items: ["Superadmin, usuario y demo_readonly usan el mismo formulario; el rol define permisos despu?s del login.","En solo lectura ver?s un badge en la barra superior (Solo lectura o Demo en m?vil).","Superadmin no tiene badge y puede modificar datos operativos."] },
    ],
  },
  {
    id: "importador-santander",
    title: "Importador bancario Santander",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "En Tesorer?a ??? Movimientos pod?s subir extractos CSV, Excel o PDF exportados desde Santander para conciliar con Copilot y Zeta." },
      { type: "bullets", items: ["Formatos: CSV, Excel (XLSX) y PDF con texto extra?ble (sin OCR).","Detecci?n USD y UYU seg?n el extracto.","Usuario y demo_readonly: vista previa permitida (no persiste ni modifica caja).","Guardar o importar extracto: solo superadmin.","Cuenta del extracto debe ser compatible con la cuenta seleccionada; si no, el guardado se bloquea.","Estados por fila: Coincide, Falta en Copilot, Falta en Zeta, Posible coincidencia.","Preview no crea recibos en Zeta ni movimientos de caja autom?ticos.","Para impactar caja registr? o confirm? el movimiento en Tesorer?a por separado."] },
      { type: "callout", variant: "warning", text: "Guardar requiere superadmin. La vista previa no modifica caja." },
    ],
  },
  {
    id: "rutinas",
    title: "Rutinas recomendadas",
    includeInToc: true,
    blocks: [
      {
        type: "subsection",
        title: "Copilot en 5 minutos",
        blocks: [
          { type: "steps", items: ["Abr? Hoy ??? operaci?n diaria. Muestra caja disponible, deuda de clientes y prioridad del d?a.","Mir? Acciones ??? ah? est?n las cosas concretas que conviene hacer: clientes a llamar, cobros a registrar.","Si hay clientes vencidos ??? abr? su ficha y contact? por WhatsApp o email directamente desde Copilot.","Si hay pagos pr?ximos ??? entr? a Tesorer?a para ver caja real y confirmar que est?n cubiertos.","Si quer?s an?lisis y reportes ??? Dashboard Resumen o Finanzas; Cartera para deuda detallada y antig?edad."] },
        ],
      },
      {
        type: "subsection",
        title: "Flujo recomendado del d?a",
        blocks: [
          { type: "paragraph", text: "Si solo ten?s 10 minutos, hac? esto en orden." },
          { type: "steps", items: [] },
        ],
      },
    ],
  },
  {
    id: "faq",
    title: "Preguntas frecuentes",
    includeInToc: true,
    blocks: [
      {
        type: "subsection",
        title: "?Copilot reemplaza a mi contador?",
        blocks: [
          { type: "paragraph", text: "No. Copilot te ayuda a leer la situaci?n del negocio y tomar decisiones. Tu contador sigue siendo quien valida, cierra y declara." },
        ],
      },
      {
        type: "subsection",
        title: "?Por qu? Finanzas y Tesorer?a pueden mostrar n?meros distintos?",
        blocks: [
          { type: "paragraph", text: "Finanzas muestra proyecciones y acumulados hist?ricos. Tesorer?a muestra la caja operativa que registraste. Son perspectivas distintas del mismo negocio." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? significa Estado: Atenci?n?",
        blocks: [
          { type: "paragraph", text: "Que hay algo para revisar. No es una emergencia, pero conviene leer el detalle y ver si hay acciones pendientes." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? pasa si el sistema contable falla?",
        blocks: [
          { type: "paragraph", text: "Copilot usa los ?ltimos datos disponibles y muestra el problema en Operacional. Los datos anteriores siguen siendo v?lidos. El sistema se recupera solo cuando la conexi?n vuelve." },
        ],
      },
      {
        type: "subsection",
        title: "?Cada cu?nto se actualizan los datos?",
        blocks: [
          { type: "paragraph", text: "Los datos cr?ticos (saldos, facturas, recibos) se actualizan autom?ticamente cada 2 horas." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? significa marcar una alerta como le?da?",
        blocks: [
          { type: "paragraph", text: "Que ya la viste. No borra la alerta ??? queda en el historial para consultarla cuando quieras." },
        ],
      },
      {
        type: "subsection",
        title: "?D?nde veo qui?n me debe?",
        blocks: [
          { type: "paragraph", text: "En Cartera (/copilot/cartera) y Clientes (/copilot/clientes)." },
        ],
      },
      {
        type: "subsection",
        title: "?D?nde veo qu? tengo que pagar?",
        blocks: [
          { type: "paragraph", text: "En Tesorer?a ??? Pagos (/copilot/tesoreria?section=pagos)." },
        ],
      },
      {
        type: "subsection",
        title: "?D?nde veo qu? hacer primero?",
        blocks: [
          { type: "paragraph", text: "En Acciones (/copilot/acciones)." },
        ],
      },
      {
        type: "subsection",
        title: "?D?nde veo si los datos est?n actualizados?",
        blocks: [
          { type: "paragraph", text: "En Operacional (/copilot/operacional)." },
        ],
      },
      {
        type: "subsection",
        title: "?Los agentes pueden modificar datos?",
        blocks: [
          { type: "paragraph", text: "No. En esta versi?n solo leen informaci?n y sugieren acciones. Vos decid?s qu? hacer." },
        ],
      },
      {
        type: "subsection",
        title: "?El agente env?a WhatsApp o emails?",
        blocks: [
          { type: "paragraph", text: "No. Puede llevarte al cliente o a la acci?n correspondiente, pero no env?a mensajes autom?ticamente." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? pasa si Zeta falla y uso el agente?",
        blocks: [
          { type: "paragraph", text: "El agente puede mostrar informaci?n con los ?ltimos datos disponibles y recomendar revisar Operacional. No inventa datos nuevos." },
        ],
      },
      {
        type: "subsection",
        title: "Copi? o envi? un mensaje al cliente. ?Qu? hago ahora?",
        blocks: [
          { type: "paragraph", text: "Si usaste la card Enviar estado de cuenta, Copilot te va a ofrecer el bot?n Registrar gesti?n autom?ticamente. Hac? clic, revis? el pre-llenado (canal y nota) y guard?. Si no usaste esa card, abr? la ficha del cliente, and? a Gesti?n de cobranza y registr? manualmente: canal, resultado (por ejemplo 'Contactado') y una nota. Eso queda en el historial y lo usan Acciones y Agentes para saber que el cliente ya fue contactado." },
        ],
      },
      {
        type: "subsection",
        title: "?Registrar una gesti?n modifica la deuda del cliente?",
        blocks: [
          { type: "paragraph", text: "No. Registrar una gesti?n es solo un seguimiento operativo. No modifica facturas, saldos ni pagos. Para marcar un pago, hacelo desde el sistema contable (Zeta)." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? pasa si un cliente prometi? pagar?",
        blocks: [
          { type: "paragraph", text: "Copilot lo muestra como seguimiento de baja prioridad mientras la fecha no lleg?. Si llega la fecha y la deuda sigue abierta, lo muestra como prioridad cr?tica para que lo verifiques. Registrar una promesa de pago no marca ninguna factura como pagada." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? pasa si cargo una fecha de pr?ximo seguimiento?",
        blocks: [
          { type: "paragraph", text: "Cuando llega ese d?a, Copilot lo muestra como prioridad alta en los Agentes y en Acciones. Es un recordatorio operativo ??? no ejecuta ninguna acci?n autom?tica." },
        ],
      },
      {
        type: "subsection",
        title: "?Qu? es la Agenda de cobranza y c?mo la uso?",
        blocks: [
          { type: "paragraph", text: "Es una pesta?a dentro de Acciones que agrupa todos los seguimientos, promesas y contactos recientes en un solo lugar. La encontr?s en Acciones ??? pesta?a 'Agenda de cobranza', o entrando directo a /copilot/acciones?tab=agenda. Tambi?n aparece resumida en Hoy: una card con counts de vencidos, hoy, pr?ximos y promesas. Filtr? por categor?a y hac? clic en Ver cliente para ir a la ficha. Solo muestra lo que vos registraste ??? no genera datos ni modifica deuda." },
        ],
      },
    ],
  },
  {
    id: "dashboard",
    title: "Dashboard Resumen ??? An?lisis ejecutivo consolidado",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Dashboard Resumen es la vista de an?lisis y reportes: ventas, cobros, deuda, caja y evoluci?n mensual. Complementa a Hoy (operaci?n del d?a) y a Finanzas (an?lisis profundo): KPIs consolidados con gr?ficos interactivos." },
      { type: "callout", variant: "info", text: "Fuente y trazabilidad ??? misma tira compacta que Hoy: Fuente Zeta, ?ltima actualizaci?n relativa y per?odo seleccionado." },
      { type: "callout", variant: "tip", text: "Si el per?odo no tiene movimiento, un estado vac?o explica por qu?, qu? hacer y qu? ver?s cuando haya datos." },
      { type: "callout", variant: "tip", text: "Us? el filtro de moneda (UYU / USD / UYU + USD separado / USD consolidado) y el selector de per?odo para ajustar la lectura. Los gr?ficos de tendencia muestran un bucket por mes para cada mes del per?odo seleccionado." },
      { type: "bullets", items: ["Facturado del per?odo ??? facturas emitidas dentro del rango seleccionado, neto de notas de cr?dito. Depende del per?odo.","Cobrado del per?odo ??? recibos registrados en Zeta dentro del rango seleccionado. Depende del per?odo.","Pendiente del per?odo ??? facturado menos cobrado dentro del rango seleccionado. No es deuda acumulada ni cartera pendiente actual. Puede ser negativo si hubo cobros de facturas anteriores.","Cartera pendiente actual ??? suma de todas las facturas pendientes al d?a de hoy. No est? limitada por el rango de fechas seleccionado.","Deuda vencida total ??? parte de la cartera pendiente cuya fecha de vencimiento ya pas?. No depende del per?odo seleccionado.","Caja disponible ??? dinero disponible actual en Tesorer?a. Es el saldo operativo registrado, no una proyecci?n.","Caja proyectada ??? saldo estimado luego de descontar pagos programados pr?ximos. Proyecci?n operativa, no saldo bancario actual. Si no hay pagos programados, coincide con la caja disponible."] },
      { type: "callout", variant: "info", text: "UYU y USD nunca se suman ni se convierten sin TC expl?cito. Con 'UYU + USD (separado)', cada gr?fico se muestra en dos bloques independientes (UYU y USD), cada uno con su propia escala. Con 'USD consolidado', todos los valores se convierten a USD usando el TC configurado." },
      { type: "bullets", items: ["USD consolidado ??? convierte todos los KPIs y gr?ficos a USD usando la f?rmula: USD + UYU ? TC. Al seleccionar este modo aparecen el chip de TC y el bot?n 'Editar TC'. Si a?n no hay TC guardado, se muestra un input inline para configurarlo.","Tipo de cambio (TC) ??? visible solo en modo 'USD consolidado'. Representa pesos por 1 d?lar (ej. 43,50 ??? 1 USD = 43,50 UYU). Debe ser un n?mero entre 0,01 y 999,99. En modos UYU + USD (separado), UYU o USD el chip y bot?n de TC no se muestran ??? esos modos no convierten valores.","USD consolidado ??? widgets en este modo: una sola columna USD en resumen ejecutivo, KPI cards en U$S, gr?ficos de tendencia con una sola serie, ranking de deudores y facturaci?n mergeado por cliente, estado de cartera con cartera pendiente/vencida consolidada, caja proyectada en USD consolidado, tabla de deuda activa con una fila por cliente (UYU+USD mergeados).","Movimientos recientes en USD consolidado ??? la tabla mantiene la moneda original para trazabilidad contable y agrega una columna 'Equiv. USD' con el equivalente calculado (monto_uyu ? TC para UYU, monto_usd para USD). No se pierde el Debe/Haber original.","PDF ??? el tipo de cambio solo aparece en la portada cuando el reporte se genera en modo USD consolidado. En PDFs UYU, USD o UYU + USD (separado) no se muestra TC."] },
      { type: "bullets", items: ["[1] Ventas por mes ??? evoluci?n mensual de facturaci?n neta del per?odo seleccionado. Con 'UYU + USD (separado)': dos gr?ficos separados (UYU y USD) con escalas independientes.","[2] Cobros por mes ??? evoluci?n mensual de cobros reales. Mismo comportamiento que [1].","[3] Ventas vs Cobros ??? facturado vs cobrado para el per?odo. Incluye el chip 'Cobranza: X% ? Pendiente del per?odo: Y%'. Con 'UYU + USD (separado)': dos gr?ficos separados (UYU y USD).","[4] Deuda por antig?edad ??? distribuci?n del saldo vencido por bucket basado en fecha de vencimiento: 0???30d, 31???60d, 61???90d, +90d. Con 'UYU + USD (separado)': dos gr?ficos separados.","[5] Top 10 deudores ??? con moneda 'UYU + USD (separado)' se muestran dos bloques (UYU y USD). El subt?tulo indica qu? porcentaje del total de deuda de esa moneda concentran los top 10.","[6] Top 10 facturaci?n hist?rica ??? con 'UYU + USD (separado)', dos bloques UYU/USD. Hist?rico total por cliente.","[7] Estado de cartera ??? 4 indicadores de clientes: Clientes activos, Con deuda activa, Con deuda vencida (?mbar), Al d?a (verde). Los clientes se cuentan una sola vez aunque tengan deuda en m?s de una moneda. Tambi?n muestra cartera pendiente UYU y USD por separado.","[9] Caja proyectada 30 d?as ??? l?nea de caja disponible hoy y proyecci?n despu?s de pagos programados.","[10] Efectividad de cobros ??? porcentaje de lo facturado que fue cobrado en el per?odo (cobrado / facturado)."] },
      { type: "callout", variant: "warning", text: "El gr?fico [6] 'Top 10 facturaci?n' usa facturaci?n hist?rica total del portafolio porque no hay API por per?odo por cliente. El badge 'Hist?rico total' lo indica. Para facturaci?n del per?odo us? Reportes ??? Ventas." },
      { type: "bullets", items: ["Resumen ejecutivo ??? banner coloreado con estado del negocio: 'Estado financiero: Estable / Atenci?n / Cr?tico'. Incluye una tabla compacta de KPIs (facturado, cobrado, pendiente del per?odo, cartera pendiente actual, deuda vencida, caja disponible) con valores UYU y USD en la misma fila. M?ximo 3 chips: riesgo principal, se?al positiva y acci?n sugerida.","Estado Estable ??? sin deuda vencida, sin clientes de riesgo alto y caja positiva despu?s de pagos.","Estado Atenci?n ??? hay al menos un cliente de riesgo alto, o hay deuda vencida, o la caja proyectada baja respecto a la caja disponible.","Estado Cr?tico ??? 3 o m?s clientes de riesgo alto, o la caja proyectada queda negativa."] },
      { type: "bullets", items: ["Clientes con deuda activa ??? todos los clientes con saldo pendiente, una fila por moneda. Columnas: cliente, moneda, deuda activa, deuda vencida, d?as de atraso, estado y acciones. Muestra los 10 primeros; 'Ver todos' expande la lista completa.","Movimientos recientes del per?odo ??? facturas, recibos y notas de cr?dito del per?odo seleccionado. Columnas: fecha, tipo, cliente, comprobante, moneda, debe, haber y saldo pendiente. Respeta el filtro de moneda. Muestra los 10 ?ltimos; 'Ver todos' expande."] },
      { type: "bullets", items: ["Per?odo ??? eleg?s el rango de fechas. Por defecto muestra el mes actual al d?a de hoy. Si cambi?s el per?odo, los KPIs facturado, cobrado y pendiente del per?odo se recalculan para ese rango. La secci?n de tendencia mensual muestra el rango completo seleccionado.","Moneda ??? 'UYU + USD (separado)' muestra UYU y USD por separado en cada card y gr?fico, sin conversi?n ni suma. 'Solo UYU' o 'Solo USD' filtran a una moneda. 'USD consolidado' convierte todo a USD con TC.","Los filtros no afectan Cartera pendiente actual (que siempre es all-outstanding al corte) ni el gr?fico [6] (hist?rico total)."] },
      { type: "bullets", items: ["Descargar PDF ??? el bot?n en el encabezado del Dashboard genera un PDF del per?odo actualmente seleccionado. La moneda del PDF coincide con la seleccionada en pantalla. El tipo de cambio solo se imprime en PDFs generados en modo USD consolidado. El mismo PDF puede generarse desde Reportes ??? Dashboard Resumen Ejecutivo."] },
      { type: "callout", variant: "info", text: "El Dashboard no reemplaza a Hoy (operaci?n diaria) ni a Cartera/Tesorer?a para gestionar. Es una capa de an?lisis y reportes. Para gestionar clientes, registrar cobros o confirmar pagos, us? los m?dulos correspondientes." },
    ],
  },
  {
    id: "glosario",
    title: "Glosario ??? T?rminos de deuda de clientes",
    includeInToc: true,
    blocks: [
      { type: "paragraph", text: "Referencia r?pida de los t?rminos que Copilot usa para describir la deuda de clientes. Cada t?rmino tiene un significado preciso para evitar confusi?n entre saldo, vencimiento y estado." },
    ],
  },
];

export const COPILOT_MANUAL_FIVE_MINUTE_STEPS: string[] = [
  "Abr? Hoy ??? operaci?n diaria. Muestra caja disponible, deuda de clientes y prioridad del d?a.",
  "Mir? Acciones ??? ah? est?n las cosas concretas que conviene hacer: clientes a llamar, cobros a registrar.",
  "Si hay clientes vencidos ??? abr? su ficha y contact? por WhatsApp o email directamente desde Copilot.",
  "Si hay pagos pr?ximos ??? entr? a Tesorer?a para ver caja real y confirmar que est?n cubiertos.",
  "Si quer?s an?lisis y reportes ??? Dashboard Resumen o Finanzas; Cartera para deuda detallada y antig?edad."
];

export const COPILOT_MANUAL_DAILY_FLOW = [] as const;

export const COPILOT_MANUAL_FAQ: Array<{ q: string; a: string }> = [
  {
    "q": "?Copilot reemplaza a mi contador?",
    "a": "No. Copilot te ayuda a leer la situaci?n del negocio y tomar decisiones. Tu contador sigue siendo quien valida, cierra y declara."
  },
  {
    "q": "?Por qu? Finanzas y Tesorer?a pueden mostrar n?meros distintos?",
    "a": "Finanzas muestra proyecciones y acumulados hist?ricos. Tesorer?a muestra la caja operativa que registraste. Son perspectivas distintas del mismo negocio."
  },
  {
    "q": "?Qu? significa Estado: Atenci?n?",
    "a": "Que hay algo para revisar. No es una emergencia, pero conviene leer el detalle y ver si hay acciones pendientes."
  },
  {
    "q": "?Qu? pasa si el sistema contable falla?",
    "a": "Copilot usa los ?ltimos datos disponibles y muestra el problema en Operacional. Los datos anteriores siguen siendo v?lidos. El sistema se recupera solo cuando la conexi?n vuelve."
  },
  {
    "q": "?Cada cu?nto se actualizan los datos?",
    "a": "Los datos cr?ticos (saldos, facturas, recibos) se actualizan autom?ticamente cada 2 horas."
  },
  {
    "q": "?Qu? significa marcar una alerta como le?da?",
    "a": "Que ya la viste. No borra la alerta ??? queda en el historial para consultarla cuando quieras."
  },
  {
    "q": "?D?nde veo qui?n me debe?",
    "a": "En Cartera (/copilot/cartera) y Clientes (/copilot/clientes)."
  },
  {
    "q": "?D?nde veo qu? tengo que pagar?",
    "a": "En Tesorer?a ??? Pagos (/copilot/tesoreria?section=pagos)."
  },
  {
    "q": "?D?nde veo qu? hacer primero?",
    "a": "En Acciones (/copilot/acciones)."
  },
  {
    "q": "?D?nde veo si los datos est?n actualizados?",
    "a": "En Operacional (/copilot/operacional)."
  },
  {
    "q": "?Los agentes pueden modificar datos?",
    "a": "No. En esta versi?n solo leen informaci?n y sugieren acciones. Vos decid?s qu? hacer."
  },
  {
    "q": "?El agente env?a WhatsApp o emails?",
    "a": "No. Puede llevarte al cliente o a la acci?n correspondiente, pero no env?a mensajes autom?ticamente."
  },
  {
    "q": "?Qu? pasa si Zeta falla y uso el agente?",
    "a": "El agente puede mostrar informaci?n con los ?ltimos datos disponibles y recomendar revisar Operacional. No inventa datos nuevos."
  },
  {
    "q": "Copi? o envi? un mensaje al cliente. ?Qu? hago ahora?",
    "a": "Si usaste la card Enviar estado de cuenta, Copilot te va a ofrecer el bot?n Registrar gesti?n autom?ticamente. Hac? clic, revis? el pre-llenado (canal y nota) y guard?. Si no usaste esa card, abr? la ficha del cliente, and? a Gesti?n de cobranza y registr? manualmente: canal, resultado (por ejemplo 'Contactado') y una nota. Eso queda en el historial y lo usan Acciones y Agentes para saber que el cliente ya fue contactado."
  },
  {
    "q": "?Registrar una gesti?n modifica la deuda del cliente?",
    "a": "No. Registrar una gesti?n es solo un seguimiento operativo. No modifica facturas, saldos ni pagos. Para marcar un pago, hacelo desde el sistema contable (Zeta)."
  },
  {
    "q": "?Qu? pasa si un cliente prometi? pagar?",
    "a": "Copilot lo muestra como seguimiento de baja prioridad mientras la fecha no lleg?. Si llega la fecha y la deuda sigue abierta, lo muestra como prioridad cr?tica para que lo verifiques. Registrar una promesa de pago no marca ninguna factura como pagada."
  },
  {
    "q": "?Qu? pasa si cargo una fecha de pr?ximo seguimiento?",
    "a": "Cuando llega ese d?a, Copilot lo muestra como prioridad alta en los Agentes y en Acciones. Es un recordatorio operativo ??? no ejecuta ninguna acci?n autom?tica."
  },
  {
    "q": "?Qu? es la Agenda de cobranza y c?mo la uso?",
    "a": "Es una pesta?a dentro de Acciones que agrupa todos los seguimientos, promesas y contactos recientes en un solo lugar. La encontr?s en Acciones ??? pesta?a 'Agenda de cobranza', o entrando directo a /copilot/acciones?tab=agenda. Tambi?n aparece resumida en Hoy: una card con counts de vencidos, hoy, pr?ximos y promesas. Filtr? por categor?a y hac? clic en Ver cliente para ir a la ficha. Solo muestra lo que vos registraste ??? no genera datos ni modifica deuda."
  }
];
